"""Enterprise releases review coordination delivery and annotations

Revision ID: 9b7798dcda5b
Revises: f484e73f04f0
Create Date: 2026-09-10 14:56:21.672679
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9b7798dcda5b'
down_revision: Union[str, Sequence[str], None] = 'f484e73f04f0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_versions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_dataset_versions_org_id'), 'dataset_versions', ['org_id'], unique=False)
    op.create_table('fair_turns',
    sa.Column('last_started', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_fair_turns_org_id'), 'fair_turns', ['org_id'], unique=False)
    op.create_table('quota_reservations',
    sa.Column('resource_key', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'resource_key')
    )
    op.create_index(op.f('ix_quota_reservations_org_id'), 'quota_reservations', ['org_id'], unique=False)
    op.create_table('rate_buckets',
    sa.Column('principal', sa.String(length=80), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'principal', 'window')
    )
    op.create_index(op.f('ix_rate_buckets_org_id'), 'rate_buckets', ['org_id'], unique=False)
    op.create_table('service_accounts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_service_accounts_org_id'), 'service_accounts', ['org_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_suppliers_org_id'), 'suppliers', ['org_id'], unique=False)
    op.create_table('workflow_settings',
    sa.Column('require_claim', sa.Boolean(), nullable=False),
    sa.Column('claim_seconds', sa.Integer(), nullable=False),
    sa.Column('queue_limit', sa.Integer(), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_workflow_settings_org_id'), 'workflow_settings', ['org_id'], unique=False)
    op.create_table('batch_result_states',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'batch_id'], ['batches.org_id', 'batches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'batch_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_batch_result_states_org_id'), 'batch_result_states', ['org_id'], unique=False)
    op.create_table('batch_suppliers',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'batch_id'], ['batches.org_id', 'batches.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'supplier_id'], ['suppliers.org_id', 'suppliers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'batch_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_batch_suppliers_org_id'), 'batch_suppliers', ['org_id'], unique=False)
    op.create_table('catalog_identities',
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'catalog_id'], ['catalogs.org_id', 'catalogs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_identities_org_id'), 'catalog_identities', ['org_id'], unique=False)
    op.create_table('integrations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_cipher', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'account_id'], ['service_accounts.org_id', 'service_accounts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_table('sampling_rounds',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'dataset_id'], ['dataset_versions.org_id', 'dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'dataset_id', 'strategy', 'seed', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_sampling_rounds_org_id'), 'sampling_rounds', ['org_id'], unique=False)
    op.create_table('service_access',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'account_id'], ['service_accounts.org_id', 'service_accounts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_service_access_org_id'), 'service_access', ['org_id'], unique=False)
    op.create_table('template_suppliers',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'supplier_id'], ['suppliers.org_id', 'suppliers.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'template_id'], ['mapping_templates.org_id', 'mapping_templates.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'template_id')
    )
    op.create_index(op.f('ix_template_suppliers_org_id'), 'template_suppliers', ['org_id'], unique=False)
    op.create_table('catalog_activations',
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'catalog_id'], ['catalogs.org_id', 'catalogs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'catalog_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_activations_org_id'), 'catalog_activations', ['org_id'], unique=False)
    op.create_table('catalog_changes',
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('from_version_id', sa.String(length=36), nullable=False),
    sa.Column('to_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'catalog_id'], ['catalogs.org_id', 'catalogs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'from_version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'to_version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'from_version_id', 'to_version_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_changes_org_id'), 'catalog_changes', ['org_id'], unique=False)
    op.create_table('batch_releases',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=False),
    sa.Column('base_release_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('result_version', sa.Integer(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'base_release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'baseline_run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'batch_id'], ['batches.org_id', 'batches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'batch_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_batch_releases_org_id'), 'batch_releases', ['org_id'], unique=False)
    op.create_index('uq_current_batch_release', 'batch_releases', ['org_id','batch_id'], unique=True, sqlite_where=sa.text("status = 'PUBLISHED'"), postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('product_identities',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'identity_id'], ['catalog_identities.org_id', 'catalog_identities.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'identity_id', 'version_id'),
    sa.UniqueConstraint('org_id', 'product_id')
    )
    op.create_index(op.f('ix_product_identities_org_id'), 'product_identities', ['org_id'], unique=False)
    op.create_table('source_identities',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('stable_key', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'batch_id'], ['batches.org_id', 'batches.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'source_id'], ['source_records.org_id', 'source_records.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'source_id')
    )
    op.create_index(op.f('ix_source_identities_org_id'), 'source_identities', ['org_id'], unique=False)
    op.create_table('annotation_tasks',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('entity_key', sa.String(length=200), nullable=False),
    sa.Column('partition', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'dataset_id'], ['dataset_versions.org_id', 'dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'dataset_id', 'item_id', 'product_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_annotation_tasks_org_id'), 'annotation_tasks', ['org_id'], unique=False)
    op.create_table('coordination_events',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_coordination_events_org_id'), 'coordination_events', ['org_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry', sa.Float(), nullable=False),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('fence_token', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'integration_id'], ['integrations.org_id', 'integrations.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'integration_id', 'event_id')
    )
    op.create_index(op.f('ix_deliveries_org_id'), 'deliveries', ['org_id'], unique=False)
    op.create_table('impact_tasks',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('resource_key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'change_id'], ['catalog_changes.org_id', 'catalog_changes.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'change_id', 'resource_key'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_impact_tasks_org_id'), 'impact_tasks', ['org_id'], unique=False)
    op.create_table('release_artifacts',
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'release_id', 'kind')
    )
    op.create_index(op.f('ix_release_artifacts_org_id'), 'release_artifacts', ['org_id'], unique=False)
    op.create_table('release_events',
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_release_events_org_id'), 'release_events', ['org_id'], unique=False)
    op.create_table('review_assignments',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'item_id')
    )
    op.create_index(op.f('ix_review_assignments_org_id'), 'review_assignments', ['org_id'], unique=False)
    op.create_table('review_claims',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('holder_id', sa.String(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'item_id')
    )
    op.create_index(op.f('ix_review_claims_org_id'), 'review_claims', ['org_id'], unique=False)
    op.create_table('annotation_decisions',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'task_id'], ['annotation_tasks.org_id', 'annotation_tasks.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'task_id', 'actor_id')
    )
    op.create_index(op.f('ix_annotation_decisions_org_id'), 'annotation_decisions', ['org_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'delivery_id'], ['deliveries.org_id', 'deliveries.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'delivery_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_delivery_attempts_org_id'), 'delivery_attempts', ['org_id'], unique=False)
    op.create_table('release_rows',
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('stable_key', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'decision_id'], ['review_events.org_id', 'review_events.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'source_id'], ['source_records.org_id', 'source_records.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'release_id', 'stable_key')
    )
    op.create_index('ix_release_rows_item', 'release_rows', ['org_id', 'item_id'], unique=False)
    op.create_index(op.f('ix_release_rows_org_id'), 'release_rows', ['org_id'], unique=False)
    op.create_index('ix_release_rows_product', 'release_rows', ['org_id', 'product_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_rows_product', table_name='release_rows')
    op.drop_index(op.f('ix_release_rows_org_id'), table_name='release_rows')
    op.drop_index('ix_release_rows_item', table_name='release_rows')
    op.drop_table('release_rows')
    op.drop_index(op.f('ix_delivery_attempts_org_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_annotation_decisions_org_id'), table_name='annotation_decisions')
    op.drop_table('annotation_decisions')
    op.drop_index(op.f('ix_review_claims_org_id'), table_name='review_claims')
    op.drop_table('review_claims')
    op.drop_index(op.f('ix_review_assignments_org_id'), table_name='review_assignments')
    op.drop_table('review_assignments')
    op.drop_index(op.f('ix_release_events_org_id'), table_name='release_events')
    op.drop_table('release_events')
    op.drop_index(op.f('ix_release_artifacts_org_id'), table_name='release_artifacts')
    op.drop_table('release_artifacts')
    op.drop_index(op.f('ix_impact_tasks_org_id'), table_name='impact_tasks')
    op.drop_table('impact_tasks')
    op.drop_index(op.f('ix_deliveries_org_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_coordination_events_org_id'), table_name='coordination_events')
    op.drop_table('coordination_events')
    op.drop_index(op.f('ix_annotation_tasks_org_id'), table_name='annotation_tasks')
    op.drop_table('annotation_tasks')
    op.drop_index(op.f('ix_source_identities_org_id'), table_name='source_identities')
    op.drop_table('source_identities')
    op.drop_index(op.f('ix_product_identities_org_id'), table_name='product_identities')
    op.drop_table('product_identities')
    op.drop_index('uq_current_batch_release',table_name='batch_releases')
    op.drop_index(op.f('ix_batch_releases_org_id'), table_name='batch_releases')
    op.drop_table('batch_releases')
    op.drop_index(op.f('ix_catalog_changes_org_id'), table_name='catalog_changes')
    op.drop_table('catalog_changes')
    op.drop_index(op.f('ix_catalog_activations_org_id'), table_name='catalog_activations')
    op.drop_table('catalog_activations')
    op.drop_index(op.f('ix_template_suppliers_org_id'), table_name='template_suppliers')
    op.drop_table('template_suppliers')
    op.drop_index(op.f('ix_service_access_org_id'), table_name='service_access')
    op.drop_table('service_access')
    op.drop_index(op.f('ix_sampling_rounds_org_id'), table_name='sampling_rounds')
    op.drop_table('sampling_rounds')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_catalog_identities_org_id'), table_name='catalog_identities')
    op.drop_table('catalog_identities')
    op.drop_index(op.f('ix_batch_suppliers_org_id'), table_name='batch_suppliers')
    op.drop_table('batch_suppliers')
    op.drop_index(op.f('ix_batch_result_states_org_id'), table_name='batch_result_states')
    op.drop_table('batch_result_states')
    op.drop_index(op.f('ix_workflow_settings_org_id'), table_name='workflow_settings')
    op.drop_table('workflow_settings')
    op.drop_index(op.f('ix_suppliers_org_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_service_accounts_org_id'), table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index(op.f('ix_rate_buckets_org_id'), table_name='rate_buckets')
    op.drop_table('rate_buckets')
    op.drop_index(op.f('ix_quota_reservations_org_id'), table_name='quota_reservations')
    op.drop_table('quota_reservations')
    op.drop_index(op.f('ix_fair_turns_org_id'), table_name='fair_turns')
    op.drop_table('fair_turns')
    op.drop_index(op.f('ix_dataset_versions_org_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    # ### end Alembic commands ###
