"""v13 impact dispositions receipt deadlines and materialized views

Revision ID: b86fd0144e45
Revises: 9b7798dcda5b
Create Date: 2026-09-10 17:33:55.518875
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b86fd0144e45'
down_revision: Union[str, Sequence[str], None] = '9b7798dcda5b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_assignments',
    sa.Column('resource_key', sa.String(length=100), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'resource_key')
    )
    op.create_index(op.f('ix_todo_assignments_org_id'), 'todo_assignments', ['org_id'], unique=False)
    op.create_table('catalog_plans',
    sa.Column('from_version_id', sa.String(length=36), nullable=False),
    sa.Column('to_version_id', sa.String(length=36), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'from_version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'to_version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_plans_org_id'), 'catalog_plans', ['org_id'], unique=False)
    op.create_table('quality_snapshots',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.String(length=64), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'revision_id')
    )
    op.create_index(op.f('ix_quality_snapshots_org_id'), 'quality_snapshots', ['org_id'], unique=False)
    op.create_table('catalog_change_rows',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'change_id'], ['catalog_changes.org_id', 'catalog_changes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'change_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_change_rows_org_id'), 'catalog_change_rows', ['org_id'], unique=False)
    op.create_table('catalog_plan_rows',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_id', sa.String(length=36), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'plan_id'], ['catalog_plans.org_id', 'catalog_plans.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'proposed_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'plan_id', 'product_id')
    )
    op.create_index(op.f('ix_catalog_plan_rows_org_id'), 'catalog_plan_rows', ['org_id'], unique=False)
    op.create_index('ix_plan_row_page', 'catalog_plan_rows', ['org_id', 'plan_id', 'group', 'id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'snapshot_id'], ['quality_snapshots.org_id', 'quality_snapshots.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'snapshot_id', 'number')
    )
    op.create_index(op.f('ix_quality_issues_org_id'), 'quality_issues', ['org_id'], unique=False)
    op.create_table('release_deltas',
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('base_release_id', sa.String(length=36), nullable=True),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'base_release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'release_id'], ['batch_releases.org_id', 'batch_releases.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'release_id', 'algorithm')
    )
    op.create_index(op.f('ix_release_deltas_org_id'), 'release_deltas', ['org_id'], unique=False)
    op.create_table('release_delta_rows',
    sa.Column('delta_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'delta_id'], ['release_deltas.org_id', 'release_deltas.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'delta_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_release_delta_rows_org_id'), 'release_delta_rows', ['org_id'], unique=False)
    op.add_column('catalog_changes', sa.Column('input_hash', sa.String(length=64), server_default='', nullable=False))
    op.add_column('catalog_products', sa.Column('search_name', sa.Text(), server_default='', nullable=False))
    op.add_column('catalog_products', sa.Column('search_model', sa.String(length=300), server_default='', nullable=False))
    op.create_index('ix_product_model_prefix', 'catalog_products', ['org_id', 'version_id', 'search_model', 'id'], unique=False)
    op.add_column('deliveries', sa.Column('received_at', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('receipt_due_at', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('last_query_at', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('escalation_state', sa.String(length=30), server_default='NONE', nullable=False))
    op.create_index(op.f('ix_deliveries_receipt_due_at'), 'deliveries', ['receipt_due_at'], unique=False)
    op.add_column('impact_tasks', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('integrations', sa.Column('receipt_timeout_seconds', sa.Integer(), server_default='900', nullable=False))
    op.add_column('integrations', sa.Column('receipt_query_url', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('reconciliation_owner_id', sa.String(length=36), nullable=True))
    with op.batch_alter_table('integrations') as batch:
        batch.create_foreign_key('fk_integration_receipt_owner', 'users', ['reconciliation_owner_id'], ['id'])
    # Backfill derived columns and historical receipt deadlines without touching original evidence.
    import json,time
    from datetime import datetime
    bind=op.get_bind();cursor=''
    while True:
        rows=bind.execute(sa.text('SELECT id,normalized FROM catalog_products WHERE id>:cursor ORDER BY id LIMIT 500'),{'cursor':cursor}).all()
        if not rows:break
        values=[]
        for ident,n in rows:
            n=json.loads(n) if isinstance(n,str) else n
            values.append({'ident':ident,'name':str(n.get('name') or '').casefold(),'model':str(n.get('model') or '').casefold()})
        bind.execute(sa.text('UPDATE catalog_products SET search_name=:name,search_model=:model WHERE id=:ident'),values);cursor=rows[-1][0]
    for ident,created in bind.execute(sa.text("SELECT id,created_at FROM deliveries WHERE status='RECEIVED'")):
        stamp=datetime.fromisoformat(created).timestamp()
        bind.execute(sa.text("UPDATE deliveries SET received_at=:stamp,receipt_due_at=:due,escalation_state='MIGRATED_AWAITING' WHERE id=:ident"),{'stamp':stamp,'due':time.time()+900,'ident':ident})
    # v1.2 release impacts could be closed from an unrelated single review.
    # Preserve that evidence for audit, and require a real release disposition.
    impacts=sa.table('impact_tasks',sa.column('id',sa.String),sa.column('release_id',sa.String),sa.column('kind',sa.String),sa.column('status',sa.String),sa.column('resolution',sa.JSON))
    for row in bind.execute(sa.select(impacts).where(impacts.c.release_id.is_not(None),impacts.c.kind!='display',impacts.c.status=='RESOLVED')).mappings():
        prior=row['resolution'] or {}
        if not prior.get('disposition'):
            bind.execute(impacts.update().where(impacts.c.id==row['id']).values(status='OPEN',resolution={'legacy_resolution':prior,'migration_notice':'v1.2 仅记录单条审核，需补充整份发布处置依据'}))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations') as batch:
        batch.drop_constraint('fk_integration_receipt_owner', type_='foreignkey')
    op.drop_column('integrations', 'reconciliation_owner_id')
    op.drop_column('integrations', 'receipt_query_url')
    op.drop_column('integrations', 'receipt_timeout_seconds')
    op.drop_column('impact_tasks', 'version')
    op.drop_index(op.f('ix_deliveries_receipt_due_at'), table_name='deliveries')
    op.drop_column('deliveries', 'escalation_state')
    op.drop_column('deliveries', 'last_query_at')
    op.drop_column('deliveries', 'receipt_due_at')
    op.drop_column('deliveries', 'received_at')
    op.drop_index('ix_product_model_prefix', table_name='catalog_products')
    op.drop_column('catalog_products', 'search_model')
    op.drop_column('catalog_products', 'search_name')
    op.drop_column('catalog_changes', 'input_hash')
    op.drop_index(op.f('ix_release_delta_rows_org_id'), table_name='release_delta_rows')
    op.drop_table('release_delta_rows')
    op.drop_index(op.f('ix_release_deltas_org_id'), table_name='release_deltas')
    op.drop_table('release_deltas')
    op.drop_index(op.f('ix_quality_issues_org_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index('ix_plan_row_page', table_name='catalog_plan_rows')
    op.drop_index(op.f('ix_catalog_plan_rows_org_id'), table_name='catalog_plan_rows')
    op.drop_table('catalog_plan_rows')
    op.drop_index(op.f('ix_catalog_change_rows_org_id'), table_name='catalog_change_rows')
    op.drop_table('catalog_change_rows')
    op.drop_index(op.f('ix_quality_snapshots_org_id'), table_name='quality_snapshots')
    op.drop_table('quality_snapshots')
    op.drop_index(op.f('ix_catalog_plans_org_id'), table_name='catalog_plans')
    op.drop_table('catalog_plans')
    op.drop_index(op.f('ix_todo_assignments_org_id'), table_name='todo_assignments')
    op.drop_table('todo_assignments')
    # ### end Alembic commands ###
