"""initial tenant schema

Revision ID: d8c4c3aad74d
Revises:
Create Date: 2026-09-10 11:02:03.370620
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd8c4c3aad74d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_key'), 'login_attempts', ['key'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dual_review', sa.Boolean(), nullable=False),
    sa.Column('default_policy_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_locks',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('batches',
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_batches_org_id'), 'batches', ['org_id'], unique=False)
    op.create_table('catalogs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalogs_org_id'), 'catalogs', ['org_id'], unique=False)
    op.create_table('files',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('sheets', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_files_org_id'), 'files', ['org_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'user_id', 'route', 'key')
    )
    op.create_index(op.f('ix_idempotency_keys_org_id'), 'idempotency_keys', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_table('outbox',
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_outbox_org_id'), 'outbox', ['org_id'], unique=False)
    op.create_table('policies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_table('batch_revisions',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('sheet', sa.String(length=200), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('exclusion_rows', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'batch_id'], ['batches.org_id', 'batches.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'file_id'], ['files.org_id', 'files.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'batch_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_batch_revisions_org_id'), 'batch_revisions', ['org_id'], unique=False)
    op.create_table('catalog_versions',
    sa.Column('catalog_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'catalog_id'], ['catalogs.org_id', 'catalogs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'file_id'], ['files.org_id', 'files.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'catalog_id', 'number'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_catalog_versions_org_id'), 'catalog_versions', ['org_id'], unique=False)
    op.create_table('catalog_products',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=200), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'version_id', 'sku')
    )
    op.create_index(op.f('ix_catalog_products_org_id'), 'catalog_products', ['org_id'], unique=False)
    op.create_index(op.f('ix_catalog_products_version_id'), 'catalog_products', ['version_id'], unique=False)
    op.create_table('match_runs',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_version_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('retry_of', sa.String(length=36), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('timings', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'catalog_version_id'], ['catalog_versions.org_id', 'catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'policy_id'], ['policies.org_id', 'policies.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_match_runs_org_id'), 'match_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_match_runs_status'), 'match_runs', ['status'], unique=False)
    op.create_index('ix_runs_org_created', 'match_runs', ['org_id', 'created_at', 'id'], unique=False)
    op.create_table('source_records',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=200), nullable=False),
    sa.Column('generated_sku', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'revision_id', 'row_no')
    )
    op.create_index(op.f('ix_source_records_org_id'), 'source_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_source_records_revision_id'), 'source_records', ['revision_id'], unique=False)
    op.create_table('exports',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_exports_org_id'), 'exports', ['org_id'], unique=False)
    op.create_table('match_items',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('suggestion', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_decision_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'source_id'], ['source_records.org_id', 'source_records.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'run_id', 'source_id')
    )
    op.create_index('ix_items_filter', 'match_items', ['org_id', 'run_id', 'suggestion', 'id'], unique=False)
    op.create_index(op.f('ix_match_items_org_id'), 'match_items', ['org_id'], unique=False)
    op.create_table('run_chunks',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('fence_token', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retry_after', sa.Float(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'run_id', 'number')
    )
    op.create_index(op.f('ix_run_chunks_org_id'), 'run_chunks', ['org_id'], unique=False)
    op.create_index(op.f('ix_run_chunks_run_id'), 'run_chunks', ['run_id'], unique=False)
    op.create_table('candidates',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'item_id', 'product_id')
    )
    op.create_index(op.f('ix_candidates_item_id'), 'candidates', ['item_id'], unique=False)
    op.create_index(op.f('ix_candidates_org_id'), 'candidates', ['org_id'], unique=False)
    op.create_table('export_rows',
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('item_version', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'export_id'], ['exports.org_id', 'exports.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'export_id', 'row_no'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_export_rows_org_id'), 'export_rows', ['org_id'], unique=False)
    op.create_table('review_events',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('selection_source', sa.String(length=30), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'item_id', 'seq')
    )
    op.create_index(op.f('ix_review_events_org_id'), 'review_events', ['org_id'], unique=False)
    op.create_table('mappings',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('valid_to', sa.String(length=40), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'decision_id'], ['review_events.org_id', 'review_events.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'product_id'], ['catalog_products.org_id', 'catalog_products.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'source_id'], ['source_records.org_id', 'source_records.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_mappings_org_id'), 'mappings', ['org_id'], unique=False)
    op.create_index('uq_active_mapping', 'mappings', ['org_id', 'item_id'], unique=True, sqlite_where=sa.text('valid_to IS NULL'), postgresql_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_mapping', table_name='mappings', sqlite_where=sa.text('valid_to IS NULL'), postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_mappings_org_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_review_events_org_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_export_rows_org_id'), table_name='export_rows')
    op.drop_table('export_rows')
    op.drop_index(op.f('ix_candidates_org_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_item_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_run_chunks_run_id'), table_name='run_chunks')
    op.drop_index(op.f('ix_run_chunks_org_id'), table_name='run_chunks')
    op.drop_table('run_chunks')
    op.drop_index(op.f('ix_match_items_org_id'), table_name='match_items')
    op.drop_index('ix_items_filter', table_name='match_items')
    op.drop_table('match_items')
    op.drop_index(op.f('ix_exports_org_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_source_records_revision_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_org_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('ix_runs_org_created', table_name='match_runs')
    op.drop_index(op.f('ix_match_runs_status'), table_name='match_runs')
    op.drop_index(op.f('ix_match_runs_org_id'), table_name='match_runs')
    op.drop_table('match_runs')
    op.drop_index(op.f('ix_catalog_products_version_id'), table_name='catalog_products')
    op.drop_index(op.f('ix_catalog_products_org_id'), table_name='catalog_products')
    op.drop_table('catalog_products')
    op.drop_index(op.f('ix_catalog_versions_org_id'), table_name='catalog_versions')
    op.drop_table('catalog_versions')
    op.drop_index(op.f('ix_batch_revisions_org_id'), table_name='batch_revisions')
    op.drop_table('batch_revisions')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_outbox_org_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_idempotency_keys_org_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_files_org_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_catalogs_org_id'), table_name='catalogs')
    op.drop_table('catalogs')
    op.drop_index(op.f('ix_batches_org_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('scheduler_locks')
    op.drop_table('organizations')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_login_attempts_key'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
