"""Import jobs correction drafts policy evaluation and operations

Revision ID: f484e73f04f0
Revises: d8c4c3aad74d
Create Date: 2026-09-10 12:20:30.917338
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f484e73f04f0'
down_revision: Union[str, Sequence[str], None] = 'd8c4c3aad74d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_templates',
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'supplier', 'name', 'number')
    )
    op.create_index(op.f('ix_mapping_templates_org_id'), 'mapping_templates', ['org_id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_policy_evaluations_org_id'), 'policy_evaluations', ['org_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_key', sa.Text(), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=False),
    sa.Column('fence_token', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'file_id'], ['files.org_id', 'files.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'kind', 'cache_key')
    )
    op.create_index(op.f('ix_import_jobs_org_id'), 'import_jobs', ['org_id'], unique=False)
    op.create_table('correction_drafts',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('submitted_revision_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'source_id'], ['source_records.org_id', 'source_records.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'submitted_revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'run_id', 'source_id', 'actor_id')
    )
    op.create_index(op.f('ix_correction_drafts_org_id'), 'correction_drafts', ['org_id'], unique=False)
    op.create_table('revision_lineage',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=36), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_links', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'parent_revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'parent_run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'revision_id'], ['batch_revisions.org_id', 'batch_revisions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id'),
    sa.UniqueConstraint('org_id', 'revision_id')
    )
    op.create_index(op.f('ix_revision_lineage_org_id'), 'revision_lineage', ['org_id'], unique=False)
    op.create_table('shadow_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'evaluation_id'], ['policy_evaluations.org_id', 'policy_evaluations.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_shadow_runs_org_id'), 'shadow_runs', ['org_id'], unique=False)
    op.create_table('artifact_deletions',
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.String(length=40), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id', 'export_id'], ['exports.org_id', 'exports.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'export_id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_artifact_deletions_org_id'), 'artifact_deletions', ['org_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.String(length=100), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'item_id'], ['match_items.org_id', 'match_items.id'], ),
    sa.ForeignKeyConstraint(['org_id', 'run_id'], ['match_runs.org_id', 'match_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'id')
    )
    op.create_index(op.f('ix_usage_events_org_id'), 'usage_events', ['org_id'], unique=False)
    op.create_index('ix_items_run_page', 'match_items', ['org_id', 'run_id', 'id'], unique=False)
    op.create_index('ix_items_status_page', 'match_items', ['org_id', 'run_id', 'status', 'id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_status_page', table_name='match_items')
    op.drop_index('ix_items_run_page', table_name='match_items')
    op.drop_index(op.f('ix_usage_events_org_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_artifact_deletions_org_id'), table_name='artifact_deletions')
    op.drop_table('artifact_deletions')
    op.drop_index(op.f('ix_shadow_runs_org_id'), table_name='shadow_runs')
    op.drop_table('shadow_runs')
    op.drop_index(op.f('ix_revision_lineage_org_id'), table_name='revision_lineage')
    op.drop_table('revision_lineage')
    op.drop_index(op.f('ix_correction_drafts_org_id'), table_name='correction_drafts')
    op.drop_table('correction_drafts')
    op.drop_index(op.f('ix_import_jobs_org_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_policy_evaluations_org_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_mapping_templates_org_id'), table_name='mapping_templates')
    op.drop_table('mapping_templates')
    # ### end Alembic commands ###
