<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import {api,post,key,hasRole,fields} from './api'
const datasets=ref<any[]>([]),dataset=ref(''),tasks=ref<any[]>([]),selected=ref<any>(null),cursor=ref<string|null>(null),createOpen=ref(false),pairOpen=ref(false),label=ref('MATCH'),reason=ref(''),started=ref(Date.now()),dispute=ref<any>(null),rounds=ref<any[]>([])
const form=ref({name:'',source_type:'simulation',evidence:'',entity_grouping_rule:'',split_seed:42}),runs=ref<any[]>([]),run=ref(''),items=ref<any[]>([]),item=ref<any>(null),product=ref(''),entity=ref(''),strategy=ref('random'),budget=ref(100),evaluations=ref<any[]>([]),evaluation=ref('')
async function act(fn:()=>Promise<any>){try{await fn()}catch(e:any){ElMessage.error(e.message)}}
async function load(){datasets.value=(await api('/datasets')).items;if(hasRole('admin'))evaluations.value=(await api('/policy-evaluations')).items;if(!dataset.value)dataset.value=datasets.value[0]?.id||'';if(dataset.value)await loadTasks()}
async function loadTasks(append=false){const r=await api('/datasets/'+dataset.value+'/tasks'+(append&&cursor.value?'?cursor='+cursor.value:''));tasks.value=append?[...tasks.value,...r.items]:r.items;cursor.value=r.next_cursor;if(!append){selected.value=null;dispute.value=null}if(hasRole('admin'))rounds.value=(await api('/datasets/'+dataset.value+'/rounds')).items}
function select(t:any){selected.value=t;label.value='MATCH';reason.value='';started.value=Date.now();dispute.value=null}
async function create(){await act(async()=>{const d=await post('/datasets',form.value);dataset.value=d.id;createOpen.value=false;await load()})}
async function addPair(){await act(async()=>{await post('/datasets/'+dataset.value+'/pairs',{item_id:item.value.id,product_id:product.value,entity_key:entity.value});ElMessage.success('候选对已入池，按实体固定划分');await loadTasks()})}
async function decide(adjudicate=false){await act(async()=>{await post('/annotation-tasks/'+selected.value.id+(adjudicate?'/adjudicate':'/decisions'),{label:label.value,reason:reason.value,seconds:Math.max(1,Math.round((Date.now()-started.value)/1000))});ElMessage.success('独立判断已保存');await loadTasks()})}
async function openPairs(){await act(async()=>{runs.value=(await api('/runs?status=SUCCEEDED')).items;pairOpen.value=true})}
onMounted(()=>act(load))
</script>
<template><div class="enterprise-section"><div class="section-title"><div><h2>独立标注与数据集</h2><p class="muted">两位标注者独立判断，分歧交由第三人裁决。资料不足单独保留，冻结标签后才可用于独立实验。</p></div><el-button v-if="hasRole('admin')" @click="createOpen=true">新建标注数据集</el-button></div><div class="button-row"><el-select v-model="dataset" placeholder="选择标注数据集" @change="loadTasks()"><el-option v-for="d in datasets" :value="d.id" :label="d.name+' · '+(d.status==='FROZEN'?'已冻结':'标注中')"/></el-select><el-button :disabled="!dataset" @click="act(()=>loadTasks())">刷新标注</el-button><el-button v-if="hasRole('admin')" :disabled="!dataset" @click="openPairs">添加候选对</el-button><el-button v-if="hasRole('admin')" :disabled="!dataset" @click="act(async()=>{await post('/datasets/'+dataset+'/freeze');await load();ElMessage.success('数据集已冻结，学习策略仍需独立准入')})">校验并冻结</el-button></div>
<div class="enterprise-columns"><section class="panel release-list"><button v-for="t in tasks" :key="t.id" :class="{chosen:selected?.id===t.id}" @click="select(t)"><strong>{{ t.snapshot.source.name }}</strong><span>{{ t.mine?'已提交我的判断':t.status==='DISPUTED'?'等待独立裁决':t.status==='RESOLVED'?'已完成':'等待独立标注' }}</span><small>实体 {{ t.entity_key }} · {{ t.partition }}</small></button><el-button v-if="cursor" @click="loadTasks(true)">更多候选对</el-button><el-empty v-if="!tasks.length" description="尚未添加标注候选对" :image-size="50"/></section><section v-if="selected" class="panel enterprise-card grow"><h3>仅依据来源与标准商品资料判断</h3><table class="data-table"><thead><tr><th>字段</th><th>来源商品</th><th>标准商品</th></tr></thead><tbody><tr v-for="f in ['name','brand','model','ram','storage','color','region','pack_count']"><td>{{ fields[f] }}</td><td>{{ selected.snapshot.source[f]??'资料缺失' }}</td><td>{{ selected.snapshot.target[f]??'资料缺失' }}</td></tr></tbody></table><p v-if="selected.mine">我已提交：{{ {MATCH:'同一 SKU',NO_MATCH:'不同 SKU',INSUFFICIENT:'资料不足'}[selected.mine.label as 'MATCH'] }}</p><p v-if="selected.status==='RESOLVED'">最终标签：{{ selected.label }} · {{ selected.label==='INSUFFICIENT'?'不会转换成负例':'完整来源可追溯' }}</p><template v-if="selected.status==='OPEN'&&!selected.mine&&hasRole('annotator')||selected.status==='DISPUTED'&&hasRole('adjudicator')&&!selected.mine"><el-radio-group v-model="label"><el-radio-button value="MATCH">同一 SKU</el-radio-button><el-radio-button value="NO_MATCH">不同 SKU</el-radio-button><el-radio-button value="INSUFFICIENT">资料不足</el-radio-button></el-radio-group><label>独立判断依据</label><el-input v-model="reason" type="textarea" placeholder="说明关键规格或缺失资料"/><div class="button-row mt16"><el-button v-if="selected.status==='DISPUTED'" @click="act(async()=>dispute=await api('/annotation-tasks/'+selected.id+'/dispute'))">查看分歧依据</el-button><el-button type="primary" :disabled="reason.trim().length<2" @click="decide(selected.status==='DISPUTED')">{{ selected.status==='DISPUTED'?'提交独立裁决':'提交我的独立判断' }}</el-button></div><p v-for="d in dispute?.items">{{ d.label }}：{{ d.reason }}</p></template></section></div>
<details v-if="hasRole('admin')&&dataset" class="panel enterprise-card"><summary>训练池选样与预算记录</summary><p class="muted">只访问固定训练分区，各选样分支独立记录预算；分歧选样需具备冻结模型证据。工具完成不表示算法已获得业务准入。</p><div class="button-row"><el-select v-model="evaluation" placeholder="选择冻结实验模型"><el-option v-for="e in evaluations" :value="e.id" :label="e.name"/></el-select><el-button :disabled="!evaluation" @click="act(async()=>{await post('/datasets/'+dataset+'/score-training',{evaluation_id:evaluation});ElMessage.success('正在对训练池评分，完成后可使用模型选样')})">冻结训练池模型评分</el-button><el-select v-model="strategy"><el-option value="random" label="随机抽样"/><el-option value="uncertainty" label="模型不确定性"/><el-option value="disagreement" label="规则与模型分歧"/></el-select><el-input-number v-model="budget" :min="1" :max="1000"/><el-button @click="act(async()=>{await post('/datasets/'+dataset+'/sample',{strategy,budget,seed:42},key());await loadTasks()})">按预算生成下一轮</el-button></div><p v-for="r in rounds">{{ r.strategy }} · 第 {{ r.number }} 轮 · {{ r.budget.pairs }} 对 / {{ r.budget.entities }} 个实体 · 保留随机样本 {{ r.budget.random_pairs }} 对</p></details>
<el-dialog v-model="createOpen" title="建立可追溯标注数据集" width="580px"><label>名称</label><el-input v-model="form.name"/><label>数据来源资格</label><el-select v-model="form.source_type"><el-option value="simulation" label="受控模拟数据"/><el-option value="public" label="公开基准"/><el-option value="authorized" label="已获得授权的目标领域数据"/></el-select><label>授权或来源证据</label><el-input v-model="form.evidence" type="textarea"/><label>实体分组与近重复处理规则</label><el-input v-model="form.entity_grouping_rule" type="textarea"/><template #footer><el-button type="primary" :disabled="!form.name||form.evidence.length<5||form.entity_grouping_rule.length<5" @click="create">创建标注数据集</el-button></template></el-dialog>
<el-dialog v-model="pairOpen" title="将候选对加入标注池" width="650px"><label>来源运行</label><el-select v-model="run" class="full" @change="act(async()=>{items=(await api('/runs/'+run+'/items?details=false')).items;item=null;product=''})"><el-option v-for="r in runs" :value="r.id" :label="r.batch_name+' · 输入 v'+r.revision_number"/></el-select><label>来源记录</label><el-select :model-value="item?.id" class="full" @change="(id:string)=>act(async()=>{item=await api('/items/'+id+'/candidates');product=''})"><el-option v-for="i in items" :value="i.id" :label="i.source.sku+' · '+i.source.normalized.name"/></el-select><label>候选标准商品</label><el-select v-model="product" class="full"><el-option v-for="p in item?.candidates||[]" :value="p.product_id" :label="p.product.sku+' · '+p.product.normalized.name"/></el-select><label>稳定实体分组标识</label><el-input v-model="entity" placeholder="同一实体的别名与近重复必须使用相同分组"/><template #footer><el-button type="primary" :disabled="!item||!product||!entity.trim()" @click="addPair">加入候选对</el-button></template></el-dialog>
</div></template>
