<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post,hasRole} from './api'
const emit=defineEmits(['open']),catalogs=ref<any[]>([]),changes=ref<any[]>([]),impacts=ref<any[]>([]),from=ref(''),to=ref(''),oldProducts=ref<any[]>([]),newProducts=ref<any[]>([]),links=ref<Record<string,string>>({}),confirmed=ref(false),selected=ref<any>(null),cursor=ref<string|null>(null),building=ref(false)
const versions=computed(()=>catalogs.value.flatMap(c=>c.versions.map((v:any)=>({...v,label:c.name+' v'+v.number}))))
const kind:Record<string,string>={added:'新增商品',retired:'停用商品',identity:'身份或编码变化',display:'展示信息变化'}
async function act(fn:()=>Promise<any>){try{await fn()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
async function load(){const [c,j,t]=await Promise.all([api('/catalogs'),api('/catalog-changes'),api('/impact-tasks')]);catalogs.value=c.items;changes.value=j.items;impacts.value=t.items;cursor.value=t.next_cursor}
async function products(id:string){return (await api('/catalog-versions/'+id+'/identity-index')).items}
async function prepare(){building.value=true;try{const [a,b]=await Promise.all([products(from.value),products(to.value)]);oldProducts.value=a;newProducts.value=b;links.value={};const fields=['brand','model','ram','storage','color','region','pack_count'];const bySku=new Map(b.map((p:any)=>[p.sku,p]));for(const p of a){const candidate:any=bySku.get(p.sku);const n=candidate&&fields.every(f=>candidate.normalized[f]===p.normalized[f])?candidate:null;if(n)links.value[p.id]=n.id}confirmed.value=false}catch(e:any){ElMessage.error(e.message)}finally{building.value=false}}
const productOptions=computed(()=>newProducts.value.map(p=>({value:p.id,label:p.sku+' · '+p.normalized.name})))
const pageIndex=ref(0),search=ref('')
const filtered=computed(()=>oldProducts.value.filter(p=>p.sku.includes(search.value)||p.normalized.name.includes(search.value))),shown=computed(()=>filtered.value.slice(pageIndex.value*20,(pageIndex.value+1)*20))
async function submit(){await act(async()=>{await post('/catalog-changes',{from_version_id:from.value,to_version_id:to.value,links:Object.fromEntries(Object.entries(links.value).filter(([,v])=>v)),confirm_identity_links:confirmed.value});oldProducts.value=[];await load();ElMessage.success('已提交影响分析，请刷新查看结果')})}
async function activate(c:any){await act(async()=>{await ElMessageBox.confirm('启用后，停用或身份变化的旧商品会阻断新批次发布；历史发布仍绑定原标准库。','启用新标准库',{confirmButtonText:'确认启用',cancelButtonText:'取消'});await post('/catalog-changes/'+c.id+'/activate');ElMessage.success('已启用新标准库');await load()})}
onMounted(()=>act(load))
</script>
<template><div class="enterprise-section"><div class="section-title"><div><h2>标准库变更影响</h2><p class="muted">先确认跨版本商品身份，再定位受影响的映射和发布。旧发布继续保留原依据。</p></div><el-button @click="act(load)">刷新分析</el-button></div>
<section v-if="hasRole('admin')" class="panel enterprise-card"><h3>建立标准商品身份对应</h3><div class="button-row"><el-select v-model="from" placeholder="原标准库版本"><el-option v-for="v in versions" :value="v.id" :label="v.label"/></el-select><el-select v-model="to" placeholder="新标准库版本"><el-option v-for="v in versions" :value="v.id" :label="v.label"/></el-select><el-button :loading="building" :disabled="!from||!to||from===to" @click="prepare">准备待确认对应</el-button></div><template v-if="oldProducts.length"><p class="muted">相同编号且身份字段完全一致的记录已列为建议对应。请核对；改名、编号复用和替代商品需人工选择，未对应旧商品视为停用。</p><el-input v-model="search" @input="pageIndex=0" placeholder="搜索原商品编号或名称"/><div class="table-scroll"><table class="data-table"><thead><tr><th>原商品</th><th>原规格</th><th>新版本中的同一业务商品</th></tr></thead><tbody><tr v-for="p in shown"><td>{{ p.sku }}<small class="cell-sub">{{ p.normalized.name }}</small></td><td>{{ p.normalized.model }} / {{ p.normalized.ram }} / {{ p.normalized.storage }} / {{ p.normalized.color }} / {{ p.normalized.region }}</td><td><el-select-v2 v-model="links[p.id]" filterable clearable placeholder="停用 / 尚未对应" :options="productOptions" style="min-width:280px"/></td></tr></tbody></table></div><el-pagination :current-page="pageIndex+1" @current-change="(p:number)=>pageIndex=p-1" layout="prev,pager,next" :page-size="20" :total="filtered.length"/><p>原商品 {{ oldProducts.length }} 件，已选择对应 {{ Object.values(links).filter(Boolean).length }} 件。</p><el-checkbox v-model="confirmed">我已核对商品身份对应与停用范围</el-checkbox><el-button type="primary" :disabled="!confirmed" @click="submit">提交影响分析</el-button></template></section>
<section class="panel"><table class="data-table"><thead><tr><th>版本对</th><th>执行状态</th><th>影响统计</th><th>操作</th></tr></thead><tbody><tr v-for="c in changes"><td>{{ versions.find(v=>v.id===c.from_version_id)?.label }} → {{ versions.find(v=>v.id===c.to_version_id)?.label }}</td><td>{{ c.status==='SUCCEEDED'?'分析完成':c.status==='FAILED'?'分析失败':'等待分析' }}</td><td>{{ c.report.affected_items??'—' }} 条映射 · {{ c.report.affected_releases??'—' }} 份发布</td><td><el-button @click="act(async()=>selected=await api('/catalog-changes/'+c.id))">查看变化</el-button><el-button v-if="hasRole('admin')" :disabled="c.status!=='SUCCEEDED'" @click="activate(c)">启用新版本</el-button></td></tr></tbody></table><el-empty v-if="!changes.length" description="尚未提交标准库变更分析"/></section>
<section class="panel enterprise-card"><h3>受影响记录</h3><div v-for="i in impacts" class="enterprise-issue"><div><strong>{{ kind[i.kind] }}</strong><p>{{ i.item_id?'有效映射':'历史发布' }} · {{ (i.item_id||i.release_id).slice(0,8) }} · {{ i.status==='OPEN'?'需要重新核对':i.status==='NOTICE'?'变更通知':'已处理' }}</p></div><el-button v-if="i.item_id" @click="act(async()=>{const item=await api('/items/'+i.item_id+'/candidates');emit('open',{id:item.run_id,item_id:item.id})})">查看受影响商品</el-button></div><el-empty v-if="!impacts.length" description="暂无受影响记录" :image-size="50"/><el-button v-if="cursor" @click="act(async()=>{const r=await api('/impact-tasks?cursor='+cursor);impacts.push(...r.items);cursor=r.next_cursor})">更多影响</el-button></section>
<el-dialog :model-value="!!selected" @close="selected=null" title="标准商品变化明细" width="720px"><table class="data-table"><thead><tr><th>类型</th><th>原编号</th><th>新编号</th><th>变化字段</th></tr></thead><tbody><tr v-for="c in selected?.changes"><td>{{ kind[c.kind] }}</td><td>{{ c.old_sku||'—' }}</td><td>{{ c.new_sku||'—' }}</td><td>{{ c.fields?.join('、')||'—' }}</td></tr></tbody></table><el-button v-if="selected?.next_offset!==null" @click="act(async()=>{const r=await api('/catalog-changes/'+selected.id+'?offset='+selected.next_offset);selected={...r,changes:[...selected.changes,...r.changes]}})">更多变化</el-button></el-dialog>
</div></template>
