<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post} from './api'
const emit=defineEmits(['submitted']),catalogs=ref<any[]>([]),plans=ref<any[]>([]),from=ref(''),to=ref(''),plan=ref<any>(null),group=ref(''),reason=ref(''),retired=ref<number|undefined>(),busy=ref(false),searchOptions=ref<any[]>([])
const groups:Record<string,string>={unchanged:'身份及内容一致',display:'名称或展示变化',identity:'身份字段变化',unlinked:'尚未对应'}
const unsaved=computed(()=>plan.value?.items.some((r:any)=>(r.proposed_id||null)!==(r.proposed_product?.id||null))||false)
const versions=computed(()=>catalogs.value.flatMap(c=>c.versions.filter((v:any)=>v.status==='PUBLISHED').map((v:any)=>({...v,label:c.name+' v'+v.number}))))
async function act(fn:()=>Promise<any>){busy.value=true;try{await fn()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}finally{busy.value=false}}
async function load(){const [c,p]=await Promise.all([api('/catalogs'),api('/catalog-plans')]);catalogs.value=c.items;plans.value=p.items}
async function detail(id=plan.value?.id,append=false){if(!id)return;const r=await api('/catalog-plans/'+id+'?'+new URLSearchParams({...group.value?{group:group.value}:{},...append&&plan.value?.next_cursor?{cursor:plan.value.next_cursor}:{}}));plan.value=append?{...r,items:[...plan.value.items,...r.items]}:r}
async function prepare(){await act(async()=>{const p=await post('/catalog-plans',{from_version_id:from.value,to_version_id:to.value});group.value='';retired.value=undefined;await detail(p.id);await load()})}
async function confirm(row?:any){await act(async()=>{await post('/catalog-plans/'+plan.value.id+'/confirm',{expected_version:plan.value.version,reason:reason.value,...row?{row_id:row.id,proposed_id:row.proposed_id||null}:{group:group.value}});await detail()})}
let request=0
async function search(q:string){const seq=++request;if(!q.trim()){searchOptions.value=[];return}const r=await api('/catalog-versions/'+plan.value.to_version_id+'/products?limit=30&q='+encodeURIComponent(q));if(seq===request)searchOptions.value=r.items}
async function submit(){await act(async()=>{await ElMessageBox.confirm(`将确认停用 ${retired.value} 件旧商品，并提交影响分析。请确保停用范围有业务依据。`,'确认停用范围',{confirmButtonText:'确认提交',cancelButtonText:'返回核对'});await post('/catalog-plans/'+plan.value.id+'/submit',{expected_version:plan.value.version,retired_count:retired.value,reason:reason.value});await detail();await load();emit('submitted');ElMessage.success('影响分析已提交')})}
let timer:ReturnType<typeof setInterval>|undefined
onMounted(()=>{void act(load);timer=setInterval(()=>{if(plan.value&&['QUEUED','COMPUTING'].includes(plan.value.status))void detail().catch(()=>{})},2500)})
onUnmounted(()=>clearInterval(timer))
</script>
<template><section class="panel enterprise-card"><h3>分页确认标准商品身份</h3><p class="muted">后台准备完整版本的对应建议。逐组确认后再提交；页面未加载的记录不会自动停用。</p><div class="button-row"><el-select v-model="from" placeholder="原标准库版本" aria-label="原标准库版本"><el-option v-for="v in versions" :key="v.id" :value="v.id" :label="v.label"/></el-select><el-select v-model="to" placeholder="新标准库版本" aria-label="新标准库版本"><el-option v-for="v in versions" :key="v.id" :value="v.id" :label="v.label"/></el-select><el-button :loading="busy" :disabled="!from||!to||from===to" @click="prepare">准备待确认对应</el-button><el-select placeholder="继续已有准备任务" @change="(v:string)=>act(()=>detail(v))"><el-option v-for="p in plans" :key="p.id" :value="p.id" :label="p.status+' · '+p.id.slice(0,8)"/></el-select></div>
<div v-if="plan" class="mt16"><div class="section-title"><p>准备状态：{{ {QUEUED:'排队中',COMPUTING:'正在准备',READY:'待确认',SUBMITTED:'已提交分析',FAILED:'准备失败'}[plan.status as 'READY'] }} · 已准备 {{ plan.progress }} 条</p><el-button @click="act(()=>detail())">刷新对应</el-button><el-button v-if="plan.status==='FAILED'" @click="act(async()=>{await post('/catalog-plans/'+plan.id+'/retry');await detail()})">重试准备</el-button></div><el-alert v-if="plan.error" :title="plan.error" type="error"/><template v-if="['READY','SUBMITTED'].includes(plan.status)"><div class="button-row"><el-select aria-label="确认分组" v-model="group" placeholder="全部分组" clearable @change="act(()=>detail())"><el-option v-for="(label,key) in groups" :key="key" :value="key" :label="label"/></el-select><span v-for="g in plan.groups" class="muted">{{ groups[g.group] }}：{{ g.confirmed }}/{{ g.total }} 已确认</span></div><el-input v-model="reason" class="mt16" placeholder="身份对应核对依据（确认或提交时必填）" aria-label="身份对应核对依据"/><div class="table-scroll"><table class="data-table"><thead><tr><th>旧商品 / 分组</th><th>新商品建议，可搜索修改</th><th>确认状态</th></tr></thead><tbody><tr v-for="r in plan.items" :key="r.id"><td>{{ r.old_product.sku }} · {{ r.old_product.normalized.name }}<small class="cell-sub">{{ groups[r.group] }}</small></td><td><el-select v-model="r.proposed_id" filterable remote clearable :remote-method="search" placeholder="输入新商品编号或名称" :disabled="plan.status!=='READY'"><el-option v-if="r.proposed_product" :value="r.proposed_product.id" :label="r.proposed_product.sku+' · '+r.proposed_product.normalized.name"/><el-option v-for="p in searchOptions.filter(p=>p.id!==r.proposed_product?.id)" :key="p.id" :value="p.id" :label="p.sku+' · '+p.normalized.name"/></el-select><small v-if="!r.proposed_id" class="cell-sub">将计入停用范围，需明确确认</small></td><td><el-button :disabled="!reason.trim()||plan.status!=='READY'" @click="confirm(r)">{{ r.confirmed?'重新确认本条':'确认本条' }}</el-button></td></tr></tbody></table></div><el-button v-if="plan.next_cursor" @click="act(()=>detail(plan.id,true))">加载下一页对应</el-button><p v-if="unsaved" class="muted">有修改尚未保存，请先点击对应行的“确认本条”，再确认分组或提交。</p><div class="button-row mt16"><el-button :disabled="!group||!reason.trim()||plan.status!=='READY'||unsaved" @click="confirm()">按依据确认当前分组</el-button><span>完整停用范围：{{ plan.retired_count }} 件</span><el-input-number v-model="retired" :min="0" placeholder="填写停用数量" aria-label="确认停用数量"/><el-button type="primary" :disabled="retired!==plan.retired_count||!reason.trim()||plan.status!=='READY'||unsaved||plan.groups.some((g:any)=>g.confirmed!==g.total)" @click="submit">提交影响分析</el-button></div></template></div></section></template>
