<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowRight, Download, FilePenLine, Save, ShieldCheck } from 'lucide-vue-next'
import { api, fields, key, post, put } from './api'
const props=defineProps<{run:any,initial?:any}>(),emit=defineEmits(['complete'])
const problems=ref<any[]>([]),total=ref(0),cursor=ref<string|null>(null),drafts=ref<any[]>([]),selected=ref<any>(null),form=ref<Record<string,string>>({}),evidence=ref(''),busy=ref(false),preview=ref<any>(null)
const currentDraft=computed(()=>drafts.value.find(d=>d.source_id===selected.value?.source.id))
const pending=computed(()=>drafts.value.filter(d=>!d.submitted_revision_id))
const base=computed(()=>Object.fromEntries(Object.keys(fields).map(k=>[k,String(selected.value?.source.raw[props.run.manifest.mapping[k]]??'')])) as Record<string,string>)
function select(item:any){selected.value=item;form.value={...base.value,...currentDraft.value?.fields};evidence.value=currentDraft.value?.evidence||'';preview.value=null}
async function load(append=false){try{const [p,d]=await Promise.all([api(`/runs/${props.run.id}/problems`+(append&&cursor.value?'?cursor='+cursor.value:'')),api(`/runs/${props.run.id}/corrections`)]);problems.value=append?[...problems.value,...p.items]:p.items;total.value=p.total;cursor.value=p.next_cursor;drafts.value=d.items;if(!selected.value)select(props.initial||p.items[0])}catch(e:any){ElMessage.error(e.message)}}
async function save(){if(!selected.value)return;busy.value=true;try{const changes=Object.fromEntries(Object.entries(form.value).filter(([k,v])=>v!==base.value[k]));if(!Object.keys(changes).length){ElMessage.info('请先填写需要补充或更正的字段');return}const result=await put(`/runs/${props.run.id}/corrections/${selected.value.source.id}`,{fields:changes,evidence:evidence.value,expected_version:currentDraft.value?.version||0});preview.value=result.preview;drafts.value=[...drafts.value.filter(d=>d.id!==result.id),result];void post('/usage-events',{run_id:props.run.id,item_id:selected.value.id,event:'correction'}).catch(()=>{});ElMessage.success('补数草稿已保存')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function submit(){busy.value=true;try{const result=await post(`/runs/${props.run.id}/corrections/submit`,{draft_ids:pending.value.map(d=>d.id)},key());ElMessage.success(`已创建补数版本，仅匹配 ${result.affected} 条修正记录`);emit('complete',result)}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function download(){try{const blob=await api(`/runs/${props.run.id}/corrections/return-template`);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='待补资料模板.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e:any){ElMessage.error(e.message)}}
const returned=ref<any>(null)
async function importReturn(event:Event){const input=event.target as HTMLInputElement;if(!input.files?.[0])return;busy.value=true;try{const form=new FormData();form.append('file',input.files[0]);returned.value=await api(`/runs/${props.run.id}/corrections/return`,{method:'POST',body:form});await load();ElMessage.success(returned.value.duplicate?'此文件已回收，返回原草稿，未重复创建':`已回收 ${returned.value.count} 条补数草稿，请核对后手动提交`)}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false;input.value=''}}
onMounted(()=>load())
</script>
<template><div class="correction-desk"><div class="correction-intro"><div><span class="eyebrow">资料补充</span><h3>只处理需要修正的记录</h3><p>共 {{ total }} 条问题记录 · {{ pending.length }} 条草稿待提交</p></div><el-button @click="download"><Download :size="14"/>下载问题行模板</el-button></div><div class="button-row"><label>上传回填模板（CSV / XLSX）<input type="file" accept=".csv,.xlsx" :disabled="busy" @change="importReturn" aria-label="上传回填模板"/></label><p class="muted">保留问题编号及校验列，填写修正值与资料来源；回收后仅保存草稿。</p><span v-if="returned">{{ returned.duplicate?'重复文件，已返回原草稿；':'' }}已回收 {{ returned.count }} 条，待人工确认提交</span></div><div class="correction-grid"><aside><button v-for="i in problems" :class="{selected:selected?.id===i.id}" @click="select(i)"><strong>{{ i.source.sku }} <span v-if="drafts.some(d=>d.source_id===i.source.id)" class="green-text">· 已保存</span></strong><p>{{ i.source.normalized.name }}</p><small>原始行 {{ i.source.row_no }} · {{ i.source.normalized.missing.map((f:string)=>fields[f]).join('、')||'核对来源规格' }}</small></button><el-button v-if="cursor" @click="load(true)">加载更多问题行</el-button></aside><section v-if="selected"><div class="section-title"><h4>{{ selected.source.sku }} · 来源字段</h4><span>原始行 {{ selected.source.row_no }}</span></div><p class="muted">填写经供应商或资料核实的值，并注明依据。</p><div class="mapping-grid correction-fields"><div v-for="(label,f) in fields"><label>{{ label }} <span v-if="form[f]!==base[f]" class="green-text">已修改</span></label><el-input v-model="form[f]" :aria-label="'补数'+label" :disabled="!!currentDraft?.submitted_revision_id" :placeholder="base[f]||'待补充'"/></div></div><label>资料来源 / 核实依据 *</label><el-input v-model="evidence" type="textarea" :rows="2" placeholder="例如：供应商 9 月 10 日规格说明，第 3 项" :disabled="!!currentDraft?.submitted_revision_id"/><div class="button-row"><el-button type="primary" :loading="busy" :disabled="!evidence.trim()||!!currentDraft?.submitted_revision_id" @click="save"><Save :size="14"/>保存本条草稿</el-button><span v-if="currentDraft" class="muted">草稿 v{{ currentDraft.version }}{{ currentDraft.submitted_revision_id?' · 已提交':'' }}</span></div><el-alert v-if="preview" :title="preview.missing.length||preview.issues.length?'已保存；仍有字段需要核实':'已保存；字段完整，提交后重新匹配'" :type="preview.missing.length||preview.issues.length?'warning':'success'" :closable="false"/></section><el-empty v-else description="暂无需要补充的记录"/></div><div class="wizard-footer"><p class="muted"><ShieldCheck :size="14"/>提交后生成独立补数版本，{{ pending.length }} 条记录重新匹配并由审核员复核。原版本与导出仍可追溯。</p><el-button type="primary" :loading="busy" :disabled="!pending.length" @click="submit">提交 {{ pending.length }} 条补数草稿<ArrowRight :size="14"/></el-button></div></div></template>
