<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Activity, ArchiveRestore, CheckCircle2, CircleAlert, Download, FileCheck2, FolderInput, Plus, RefreshCw, Upload } from 'lucide-vue-next'
import { api, date, hasRole, post, put, session } from './api'

const emit=defineEmits(['open-batch'])
const tab=ref('events'),sources=ref<any[]>([]),profiles=ref<any[]>([]),events=ref<any[]>([]),suppliers=ref<any[]>([])
const busy=ref(false),sourceOpen=ref(false),profileOpen=ref(false),secret=ref(''),attempts=ref<any>(null),dryRun=ref<any>(null)
const sourceForm=ref<any>({name:'',kind:'MANUAL',supplier_id:'',location:'',config:{stable_seconds:10,archive_after_success:true}})
const profileForm=ref<any>({supplier_id:'',name:'手机商品导入模板',file_type:'csv',sheet:'CSV',header_row:1,encoding:'utf-8',mapping:{sku:'商品编号',name:'商品名称',brand:'品牌',model:'型号',ram:'运行内存',storage:'存储容量',color:'颜色',region:'销售版本',pack_count:'包装数量',price:'报价',currency:'币种'},transformations:{brand:{trim:true},model:{trim:true,case:'lower'}},validations:{required:['name','brand','model'],unique:['sku']},change_note:''})
const fieldLabels:Record<string,string>={sku:'商品编号',name:'商品名称',brand:'品牌',model:'型号',ram:'运行内存',storage:'存储容量',color:'颜色',region:'销售版本',pack_count:'包装数量',price:'报价',currency:'币种'}
const sourceKinds:Record<string,string>={MANUAL:'页面上传',DIRECTORY:'监控目录',S3:'S3 / MinIO',API:'受控 API'}
const eventStatus:Record<string,string>={RECEIVED:'已接收',READY:'输入已就绪',REJECTED:'校验未通过',FAILED:'处理失败'}

async function act(fn:()=>Promise<any>){try{busy.value=true;await fn()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'操作失败')}finally{busy.value=false}}
async function load(){await act(async()=>{const [a,b,c,d]=await Promise.all([api('/ingestion-sources'),api('/import-profiles'),api('/ingestion-events'),api('/suppliers')]);sources.value=a.items;profiles.value=b.items;events.value=c.items.sort((x:any,y:any)=>y.created_at.localeCompare(x.created_at));suppliers.value=d.items})}
function supplierName(id:string){return suppliers.value.find(s=>s.id===id)?.name||'未知供应商'}
function openSource(){sourceForm.value={name:'',kind:'MANUAL',supplier_id:suppliers.value[0]?.id||'',location:'',config:{stable_seconds:10,archive_after_success:true}};sourceOpen.value=true}
async function createSource(){await act(async()=>{if(sourceForm.value.kind==='S3'&&!sourceForm.value.location)sourceForm.value.location=`${session.org}/${sourceForm.value.supplier_id}/inbox`;const result=await post('/ingestion-sources',sourceForm.value);secret.value=result.signing_secret||'';sourceOpen.value=false;await load();ElMessage.success('接入源已创建')})}
function openProfile(){profileForm.value={...profileForm.value,supplier_id:suppliers.value[0]?.id||'',change_note:''};profileOpen.value=true}
async function createProfile(){await act(async()=>{await post('/import-profiles',profileForm.value);profileOpen.value=false;await load();tab.value='profiles';ElMessage.success('配置草稿已创建，请先试运行再发布')})}
async function publishProfile(profile:any){await act(async()=>{await ElMessageBox.confirm(`发布 ${profile.name} v${profile.number}。之后到达的文件将绑定此版本。`,'发布导入配置',{confirmButtonText:'确认发布',cancelButtonText:'取消'});await post(`/import-profiles/${profile.id}/publish`,{expected_version:profile.lock_version});await load();ElMessage.success('配置版本已发布')})}
async function rollback(profile:any){await act(async()=>{const {value}=await ElMessageBox.prompt(`将基于 v${profile.number} 创建新的已发布版本，历史事件保持原配置。`,'回退配置',{inputPlaceholder:'填写回退原因',inputValidator:v=>!!v?.trim()||'请填写原因'});await post(`/import-profiles/${profile.id}/rollback`,{reason:value});await load();ElMessage.success('已创建回退版本')})}
async function check(source:any){await act(async()=>{const result=await post(`/ingestion-sources/${source.id}/check`);result.ok?ElMessage.success(result.detail):ElMessage.warning(result.detail);await load()})}
async function toggle(source:any){await act(async()=>{await put(`/ingestion-sources/${source.id}`,{active:source.status!=='ACTIVE'});await load()})}
async function uploadToSource(event:Event,source:any){const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;await act(async()=>{const form=new FormData();form.append('file',file);const result=await api(`/ingestion-sources/${source.id}/upload`,{method:'POST',body:form});await load();tab.value='events';result.duplicate?ElMessage.info('文件摘要重复，已返回原接入事件'):ElMessage.success(result.status==='READY'?'文件已生成不可变输入版本':'文件未通过校验，请下载问题报告')})}
async function dryRunFile(event:Event,profile:any){const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;await act(async()=>{const form=new FormData();form.append('file',file);const uploaded=await api('/files',{method:'POST',body:form});dryRun.value={profile,result:await post(`/import-profiles/${profile.id}/dry-run`,{file_id:uploaded.id})}})}
async function downloadErrors(row:any){await act(async()=>{const blob=await api(`/ingestion-events/${row.id}/errors`);const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`接入问题_${row.id.slice(0,8)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)})}
async function replay(row:any){await act(async()=>{const {value}=await ElMessageBox.prompt('重放沿用原事件号和原配置版本，只用于可恢复的系统失败。','重放接入事件',{inputValidator:v=>!!v?.trim()||'请填写重放原因'});await post(`/ingestion-events/${row.id}/replay`,{reason:value});await load()})}
async function showAttempts(row:any){await act(async()=>{attempts.value={event:row,items:(await api(`/ingestion-events/${row.id}/attempts`)).items}})}
onMounted(load)
</script>

<template><div class="v14-page"><div class="page-heading"><div><div class="heading-kicker">供应商文件协作</div><h1>数据接入</h1><p>管理接入源、映射版本和每一次文件处理结果。</p></div><div class="button-row"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button><el-button v-if="hasRole('operator','admin','integration_manager')" @click="openSource"><Plus :size="15"/>接入源</el-button><el-button v-if="hasRole('operator','admin')" type="primary" @click="openProfile"><Plus :size="15"/>映射配置</el-button></div></div>
<div class="v14-summary"><div><FolderInput/><span>接入源<strong>{{ sources.length }}</strong></span></div><div><FileCheck2/><span>已发布配置<strong>{{ profiles.filter(p=>p.status==='PUBLISHED').length }}</strong></span></div><div><CheckCircle2/><span>就绪事件<strong>{{ events.filter(e=>e.status==='READY').length }}</strong></span></div><div><CircleAlert/><span>待处理异常<strong>{{ events.filter(e=>['FAILED','REJECTED'].includes(e.status)).length }}</strong></span></div></div>
<div class="settings-tabs"><button v-for="(label,id) in {events:'接入事件',sources:'接入源',profiles:'映射配置'}" :class="{selected:tab===id}" @click="tab=id">{{ label }}</button></div>
<section v-if="tab==='events'" class="panel"><div class="panel-header"><div><h3>文件处理记录</h3><p class="muted">重复文件返回原事件，不重复创建业务批次。</p></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>文件与事件</th><th>接入源 / 配置</th><th>处理结果</th><th>数据摘要</th><th>时间</th><th class="align-right">操作</th></tr></thead><tbody><tr v-for="e in events"><td><strong>{{ e.filename }}</strong><small class="cell-sub mono">{{ e.external_key }} · {{ e.object_sha256.slice(0,10) }}</small></td><td>{{ e.source_name }}<small class="cell-sub">{{ e.profile_name }}</small></td><td><span class="status-pill" :class="e.status==='READY'?'SUCCEEDED':e.status==='REJECTED'?'CONFLICT':e.status">{{ eventStatus[e.status]||e.status }}</span><small class="cell-sub">{{ e.last_error }}</small></td><td>{{ e.summary.total||0 }} 行<small class="cell-sub">接收 {{ e.summary.accepted||0 }} · 拒绝 {{ e.summary.rejected||0 }} · 提示 {{ e.summary.warnings||0 }}</small></td><td>{{ date(e.created_at) }}</td><td class="align-right"><button v-if="e.batch_id" class="text-button" @click="emit('open-batch',e)">查看输入</button><button v-if="['FAILED','REJECTED'].includes(e.status)" class="text-button" @click="downloadErrors(e)"><Download :size="13"/>问题报告</button><button v-if="e.status==='FAILED'" class="text-button" @click="replay(e)"><ArchiveRestore :size="13"/>重放</button><button class="text-button muted" @click="showAttempts(e)">尝试记录</button></td></tr></tbody></table></div><el-empty v-if="!events.length" description="尚无接入事件，可从页面接入源上传第一份文件"/></section>
<section v-if="tab==='sources'" class="panel"><div class="source-grid"><article v-for="s in sources" class="source-entry"><div class="source-icon"><FolderInput :size="19"/></div><div class="grow"><div class="entry-heading"><strong>{{ s.name }}</strong><span class="status-pill" :class="s.status==='ACTIVE'?'SUCCEEDED':'CANCELLED'">{{ s.status==='ACTIVE'?'已启用':'已停用' }}</span></div><p>{{ sourceKinds[s.kind] }} · {{ supplierName(s.supplier_id) }}</p><small>{{ s.location||'由受控入口接收' }} · {{ s.event_count }} 个事件</small><small>最近成功 {{ date(s.last_success_at) }} · 连续失败 {{ s.consecutive_failures }}</small></div><div class="entry-actions"><label v-if="s.kind==='MANUAL'" class="upload-button"><Upload :size="14"/>上传文件<input type="file" accept=".csv,.xlsx" @change="uploadToSource($event,s)"/></label><el-button size="small" @click="check(s)"><Activity :size="14"/>检查</el-button><el-button size="small" @click="toggle(s)">{{ s.status==='ACTIVE'?'停用':'启用' }}</el-button></div></article></div><el-empty v-if="!sources.length" description="创建页面、目录、对象存储或 API 接入源"/></section>
<section v-if="tab==='profiles'" class="panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>配置版本</th><th>供应商</th><th>文件规则</th><th>映射与校验</th><th>状态</th><th class="align-right">操作</th></tr></thead><tbody><tr v-for="p in profiles"><td><strong>{{ p.name }} v{{ p.number }}</strong><small class="cell-sub">{{ p.change_note }}</small></td><td>{{ supplierName(p.supplier_id) }}</td><td>{{ p.file_type.toUpperCase() }} · {{ p.sheet }} · 表头第 {{ p.header_row }} 行<small class="cell-sub">{{ p.encoding }}</small></td><td>{{ Object.keys(p.mapping).length }} 个标准字段<small class="cell-sub">必填 {{ (p.validations.required||[]).map((f:string)=>fieldLabels[f]).join('、')||'无' }}</small></td><td><span class="status-pill" :class="p.status==='PUBLISHED'?'SUCCEEDED':p.status==='DRAFT'?'QUEUED':'CANCELLED'">{{ {PUBLISHED:'已发布',DRAFT:'待发布',RETIRED:'历史版本'}[p.status as 'DRAFT'] }}</span><small class="cell-sub">{{ date(p.effective_from) }}</small></td><td class="align-right"><label class="text-button upload-inline">试运行<input type="file" accept=".csv,.xlsx" @change="dryRunFile($event,p)"/></label><button v-if="p.status==='DRAFT'&&hasRole('admin')" class="text-button" @click="publishProfile(p)">发布</button><button v-if="p.status!=='PUBLISHED'&&hasRole('admin')" class="text-button muted" @click="rollback(p)">作为新版本启用</button></td></tr></tbody></table></div></section>
<el-dialog v-model="sourceOpen" title="创建接入源" width="560px"><label>接入源名称</label><el-input v-model="sourceForm.name"/><label>供应商</label><el-select v-model="sourceForm.supplier_id" class="full"><el-option v-for="s in suppliers" :value="s.id" :label="s.name"/></el-select><label>接入方式</label><el-segmented v-model="sourceForm.kind" :options="Object.entries(sourceKinds).map(([value,label])=>({value,label}))"/><template v-if="sourceForm.kind==='DIRECTORY'"><label>监控目录</label><el-input v-model="sourceForm.location" placeholder="例如 supplier-a/incoming"/><p class="muted">填写接入根目录下的相对路径。</p></template><template v-if="sourceForm.kind==='S3'"><label>对象前缀</label><el-input v-model="sourceForm.location" :placeholder="`${session.org}/${sourceForm.supplier_id}/inbox`"/></template><template #footer><el-button @click="sourceOpen=false">取消</el-button><el-button type="primary" :disabled="!sourceForm.name.trim()||!sourceForm.supplier_id" @click="createSource">创建</el-button></template></el-dialog>
<el-dialog v-model="profileOpen" title="创建映射配置版本" width="760px"><div class="form-columns"><div><label>供应商</label><el-select v-model="profileForm.supplier_id" class="full"><el-option v-for="s in suppliers" :value="s.id" :label="s.name"/></el-select></div><div><label>配置名称</label><el-input v-model="profileForm.name"/></div><div><label>文件类型</label><el-select v-model="profileForm.file_type" class="full"><el-option value="csv" label="CSV"/><el-option value="xlsx" label="Excel XLSX"/></el-select></div><div><label>工作表</label><el-input v-model="profileForm.sheet"/></div><div><label>表头行</label><el-input-number v-model="profileForm.header_row" :min="1" :max="100"/></div><div><label>编码</label><el-select v-model="profileForm.encoding"><el-option value="utf-8" label="UTF-8"/><el-option value="gb18030" label="GB18030"/></el-select></div></div><h3 class="form-subtitle">来源列映射</h3><div class="mapping-grid"><label v-for="(label,field) in fieldLabels">{{ label }}<el-input v-model="profileForm.mapping[field]" :placeholder="`来源表中的${label}列名`"/></label></div><label>变更说明</label><el-input v-model="profileForm.change_note" type="textarea" :rows="2"/><template #footer><el-button @click="profileOpen=false">取消</el-button><el-button type="primary" :disabled="!profileForm.supplier_id||!profileForm.change_note.trim()" @click="createProfile">保存草稿</el-button></template></el-dialog>
<el-dialog :model-value="!!dryRun" @close="dryRun=null" title="映射试运行结果" width="850px"><template v-if="dryRun"><div class="dry-stats"><span>预计导入<strong>{{ dryRun.result.accepted }}</strong></span><span>拒绝<strong>{{ dryRun.result.rejected }}</strong></span><span>数据提示<strong>{{ dryRun.result.warnings }}</strong></span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>原始行</th><th>来源编号</th><th>转换后商品</th><th>校验结果</th></tr></thead><tbody><tr v-for="r in dryRun.result.rows"><td>{{ r.row_no }}</td><td>{{ r.sku }}</td><td>{{ r.normalized.name }}<small class="cell-sub">{{ r.normalized.brand }} · {{ r.normalized.model }}</small></td><td><span v-for="i in r.issues" :class="i.level==='error'?'conflict-text':'muted'">{{ i.message }}<br></span><span v-if="!r.issues.length" class="green-text">通过</span></td></tr></tbody></table></div></template></el-dialog>
<el-dialog :model-value="!!attempts" @close="attempts=null" title="接入尝试记录" width="620px"><table class="data-table"><thead><tr><th>次数</th><th>阶段</th><th>结果</th><th>时间</th></tr></thead><tbody><tr v-for="a in attempts?.items"><td>{{ a.number }}</td><td>{{ a.stage }}</td><td>{{ a.status }}<small class="cell-sub">{{ a.error }}</small></td><td>{{ date(a.created_at) }}</td></tr></tbody></table></el-dialog>
<el-dialog :model-value="!!secret" @close="secret=''" title="保存 API 签名密钥" width="560px"><p>签名密钥只显示本次。服务账号还需要单独授予 <span class="mono">ingestion:write</span> 权限。</p><el-input :model-value="secret" readonly type="password" show-password/><template #footer><el-button type="primary" @click="secret=''">已保存</el-button></template></el-dialog>
</div></template>
