<script setup lang="ts">
import {ref,watch,computed} from 'vue'
import {ElMessage} from 'element-plus'
import {api,post,hasRole,date,labels} from './api'
const props=defineProps<{id:string}>(),emit=defineEmits(['close','resolved','open']),context=ref<any>(null),selected=ref(''),mode=ref('replace'),reason=ref(''),check=ref<any>(null),busy=ref(false)
const statusLabels:Record<string,string>={OPEN:'需要复核',NOTICE:'待知悉',WAITING_DOWNSTREAM:'下游待确认',LOCAL_RESOLVED:'平台内处置完成',RESOLVED:'已完成',RECONCILE:'回执超时，待对账',RECEIVED:'等待业务回执',APPLIED:'业务应用成功',PARTIAL:'部分失败',REJECTED:'对端拒绝',QUEUED:'等待通知',MANUAL:'需人工处理'}
const body=computed(()=>({reason:reason.value,expected_version:context.value?.task.version,...context.value?.task.kind==='display'?{}:context.value?.task.item_id?{replacement_item_id:selected.value}:mode.value==='revoke'?{revoke_event_id:selected.value}:{replacement_release_id:selected.value}}))
const allowed=computed(()=>hasRole(context.value?.task.item_id||context.value?.task.kind==='display'?'reviewer':'publisher'))
async function act(fn:()=>Promise<any>){busy.value=true;try{await fn()}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
watch(()=>props.id,()=>act(async()=>{context.value=await api('/impact-tasks/'+props.id+'/context');selected.value='';check.value=null}),{immediate:true})
watch([selected,reason,mode],()=>check.value=null)
async function verify(){await act(async()=>check.value=await post('/impact-tasks/'+props.id+'/preflight',body.value))}
async function resolve(){await act(async()=>{await post('/impact-tasks/'+props.id+'/resolve',body.value);context.value=await api('/impact-tasks/'+props.id+'/context');emit('resolved');ElMessage.success('处置依据已保存，交付状态继续按回执跟踪')})}
</script>
<template><el-dialog :model-value="true" @close="emit('close')" title="处理标准库影响" width="820px"><div v-if="context"><p><strong>旧商品：</strong>{{ context.old_product.sku }} · {{ context.old_product.normalized.name }}</p><p>受影响来源共 {{ context.total_affected }} 条 · 当前状态 {{ statusLabels[context.task.status]||context.task.status }}</p><p v-if="context.original_release" class="muted">原发布 v{{ context.original_release.number }} · 快照 {{ context.original_release.snapshot_hash?.slice(0,16) }} · 历史文件保留原始依据</p><table class="data-table"><thead><tr><th>稳定来源 / 编号</th><th>原审核依据</th></tr></thead><tbody><tr v-for="r in context.affected" :key="r.id"><td>{{ r.data?.source_sku||r.sku||r.stable_key }}<small class="cell-sub">{{ r.data?.source_name||r.stable_key }}</small></td><td>{{ r.data?.decision_reason||'原审核记录' }}<small class="cell-sub">{{ date(r.data?.decision_at) }} · {{ (r.decision_id||context.old_item?.current_decision_id||'').slice(0,8) }}</small></td></tr></tbody></table><el-button v-if="context.next_offset!==null&&context.next_offset!==undefined" @click="act(async()=>{const r=await api('/impact-tasks/'+id+'/context?offset='+context.next_offset);context={...r,affected:[...context.affected,...r.affected]}})">更多受影响来源</el-button>
<template v-if="['OPEN','NOTICE'].includes(context.task.status)"><el-alert title="先在新标准库下重新匹配并审核对应来源；发布影响还需生成覆盖全部来源的替代发布。" type="info" :closable="false"/><template v-if="context.task.kind!=='display'"><el-radio-group v-if="context.task.release_id" v-model="mode" class="mt16" @change="selected=''"><el-radio value="replace">使用替代发布</el-radio><el-radio value="revoke">原发布已撤销</el-radio></el-radio-group><label class="mt16">{{ context.task.item_id?'新标准库下的有效审核':'选择处置依据' }}</label><el-select v-model="selected" class="full" placeholder="选择有关联的审核或发布"><el-option v-for="r in mode==='revoke'?context.revocations:context.candidates" :key="r.id" :value="r.id" :label="r.number?'发布 v'+r.number+' · '+(labels[r.status]||r.status):(r.run_id?'审核 '+r.id.slice(0,8)+' · '+r.status:'撤销事件 '+date(r.created_at))"/></el-select><p v-if="!(mode==='revoke'?context.revocations:context.candidates)?.length" class="muted">暂无可选依据。请先完成新运行审核与发布，或由发布者撤销原发布，再刷新此待办。</p><div v-if="context.task.item_id" class="button-row"><el-button v-for="r in context.candidates" @click="emit('open',{id:r.run_id,item_id:r.id})">打开替代审核 {{ r.id.slice(0,8) }}</el-button></div></template><label>处置理由</label><el-input v-model="reason" type="textarea" aria-label="影响处置理由" placeholder="填写复核结论与业务依据"/><div class="button-row mt16"><el-button :loading="busy" :disabled="!reason.trim()||!allowed" @click="verify">完成前检查</el-button><el-button type="primary" :loading="busy" :disabled="!check?.ready||!allowed" @click="resolve">保存影响处置</el-button></div><el-alert v-for="p in check?.problems||[]" :key="p.code" :title="p.message" type="warning" :closable="false"/><el-alert v-if="check?.ready" title="关联、范围、审核及发布依据检查通过，可以保存。" type="success" :closable="false"/><p v-if="!allowed" class="muted">此处置需要{{ context.task.item_id?'审核员':'发布者' }}权限，请由对应责任人操作。</p></template>
<div v-else><p>处置理由：{{ context.task.resolution.reason }}</p><p>记录时间：{{ date(context.task.resolution.at) }} · {{ context.task.next_action||'平台内复核已完成' }}</p><p v-for="d in context.task.downstream">下游交付 {{ d.id.slice(0,8) }}：{{ statusLabels[d.status]||d.status }}</p></div></div></el-dialog></template>
