<script setup lang="ts">
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowLeft, ArrowRight, Check, FileSpreadsheet, ShieldCheck, UploadCloud } from 'lucide-vue-next'
import { api, fields, key, post } from './api'
const props=defineProps<{mode:string,batchId:string,catalogId:string,catalogs:any[],policies:any[]}>()
const emit=defineEmits(['complete','cancel'])
const step=ref(0), busy=ref(false), file=ref<any>(null), chosen=ref<File|null>(null), input=ref<HTMLInputElement|null>(null), encoding=ref('utf-8'), sheet=ref(''), header=ref(1), sample=ref<any>(null), mapping=ref<Record<string,string>>({}), quality=ref<any>(null), exclusionsConfirmed=ref(false)
const name=ref(''), supplier=ref(''), catalog=ref(props.catalogs[0]?.id||''), policy=ref(props.policies[0]?.id||'')
const config=computed(()=>({file_id:file.value?.id,sheet:sheet.value,header_row:header.value,mapping:Object.fromEntries(Object.entries(mapping.value).filter(([,v])=>v)),exclude_rows:quality.value?.error_rows||[]}))
function selectFile(event:Event){const f=(event.target as HTMLInputElement).files?.[0];if(f){chosen.value=f;name.value=f.name.replace(/\.[^.]+$/,'')}}
function drop(event:DragEvent){const f=event.dataTransfer?.files[0];if(f){chosen.value=f;name.value=f.name.replace(/\.[^.]+$/,'')}}
async function upload(){if(!chosen.value)return;busy.value=true;try{const form=new FormData();form.append('file',chosen.value);file.value=await api('/files?encoding='+encoding.value,{method:'POST',body:form});sheet.value=file.value.sheets[0];await preview();step.value=1}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function preview(){try{sample.value=await api(`/files/${file.value.id}/preview?`+new URLSearchParams({sheet:sheet.value,header_row:String(header.value)}));mapping.value=sample.value.suggested_mapping;quality.value=null}catch(e:any){ElMessage.error(e.message)}}
async function validate(){busy.value=true;try{quality.value=await post('/imports/validate?catalog='+(props.mode==='catalog'),config.value);exclusionsConfirmed.value=false;step.value=2}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
const invalid=computed(()=>!quality.value?.valid||(props.mode==='catalog'&&quality.value?.error_rows.length)|| (quality.value?.error_rows.length&&!exclusionsConfirmed.value)||!name.value.trim()||(props.mode==='batch'&&(!supplier.value.trim()||!catalog.value)))
// Retain request results on a recoverable network failure, so retry doesn't create duplicate inputs.
const savedInput=ref<any>(null), submitKey=key()
async function submit(){busy.value=true;try{
  if(props.mode==='catalog'){
    const cat=props.catalogId||savedInput.value?.catalogId||(await post('/catalogs',{name:name.value})).id
    savedInput.value={catalogId:cat}
    const version=await post(`/catalogs/${cat}/versions`,config.value)
    ElMessage.success(version.status==='DRAFT'?'标准库已校验，请由管理员发布':'已保存校验失败的版本，请修正后导入')
    emit('complete',{catalog:true})
  }else{
    if(!savedInput.value){savedInput.value=props.batchId?{revision:await post(`/batches/${props.batchId}/revisions`,config.value)}:await post('/batches',{...config.value,name:name.value,supplier:supplier.value})}
    const r=await post('/runs',{revision_id:savedInput.value.revision.id,catalog_version_id:catalog.value,policy_id:policy.value||null},submitKey)
    ElMessage.success('输入已冻结，匹配任务已提交');emit('complete',{run_id:r.id})
  }
}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
</script>

<template><div class="import-wizard"><div class="wizard-steps"><div v-for="(title,i) in ['上传文件','配置字段','校验并确认']" :class="{current:step===i,done:step>i}"><span><Check v-if="step>i" :size="15"/><template v-else>{{ i+1 }}</template></span>{{ title }}</div></div>
<div v-if="step===0"><div class="upload-zone" @dragover.prevent @drop.prevent="drop" @click="input?.click()" @keydown.enter="input?.click()" tabindex="0" role="button" aria-label="选择商品表格"><div class="upload-illustration"><UploadCloud :size="30"/></div><h3>{{ chosen?chosen.name:'拖拽商品表格到这里，或点击选择' }}</h3><p>支持 .xlsx / .csv，单文件最多 20MB</p><span v-if="chosen" class="status-pill SUCCEEDED">{{ (chosen.size/1024).toFixed(1) }} KB · 已选择</span><span v-else class="fake-button">选择文件</span><input ref="input" type="file" accept=".csv,.xlsx" @change="selectFile" hidden/></div><div class="two-columns"><div><label>CSV 文件编码</label><el-select v-model="encoding" class="full"><el-option value="utf-8" label="UTF-8（推荐）"/><el-option value="gb18030" label="GB18030（中文编码）"/></el-select></div><div class="import-hint"><ShieldCheck :size="18"/><span>保留商品编号前导零。公式单元格需先粘贴为普通值。</span></div></div><div class="wizard-footer"><el-button @click="emit('cancel')">取消</el-button><el-button type="primary" :disabled="!chosen" :loading="busy" @click="upload">上传并配置字段<ArrowRight :size="15"/></el-button></div></div>
<div v-if="step===1"><div class="two-columns"><div><label>选择工作表</label><el-select v-model="sheet" class="full" @change="preview"><el-option v-for="s in file.sheets" :value="s" :label="s"/></el-select></div><div><label>表头所在行</label><el-input-number v-model="header" :min="1" :max="100" @change="preview"/></div></div><p class="muted">已根据列名建议对应关系，请确认后继续。名称为必填字段{{ mode==='catalog'?'，标准库编号也为必填字段':'' }}。</p><div class="mapping-grid"><div v-for="(label,field) in fields"><label>{{ label }} <em v-if="field==='name'||(mode==='catalog'&&field==='sku')">*</em></label><el-select v-model="mapping[field]" clearable placeholder="未映射"><el-option v-for="h in sample?.headers" :label="h" :value="h"/></el-select></div></div><h4>原始数据预览 <small>共 {{ sample?.total }} 行</small></h4><div class="preview-table"><table class="data-table"><thead><tr><th>原始行</th><th v-for="h in sample?.headers">{{ h }}</th></tr></thead><tbody><tr v-for="r in sample?.rows.slice(0,4)"><td>{{ r.row_no }}</td><td v-for="h in sample?.headers">{{ r.values[h]||'—' }}</td></tr></tbody></table></div><div class="wizard-footer"><el-button @click="step=0"><ArrowLeft :size="14"/>上一步</el-button><el-button type="primary" :disabled="!mapping.name" :loading="busy" @click="validate">校验数据<ArrowRight :size="15"/></el-button></div></div>
<div v-if="step===2"><div class="quality-stats"><div><strong>{{ quality.total }}</strong><span>原始记录</span></div><div class="green-text"><strong>{{ quality.valid }}</strong><span>有效记录</span></div><div class="conflict-text"><strong>{{ quality.error_rows.length }}</strong><span>错误记录</span></div><div><strong>{{ quality.warning_count }}</strong><span>含质量提示</span></div></div><el-alert v-if="quality.error_rows.length" :title="mode==='catalog'?'标准库存在错误，请修正文件后重新导入':`错误行不会参与匹配：第 ${quality.error_rows.join('、')} 行`" :type="mode==='catalog'?'error':'warning'" :closable="false"/><div class="quality-table"><table class="data-table"><thead><tr><th>原始行</th><th>商品名称</th><th>校验结果</th></tr></thead><tbody><tr v-for="r in quality.rows.slice(0,12)"><td>{{ r.row_no }}</td><td>{{ r.normalized.name||'（空名称）' }}<small class="cell-sub">{{ r.sku }}</small></td><td><span v-if="!r.issues.length" class="green-text">校验通过</span><div v-for="i in r.issues" :class="i.level==='error'?'conflict-text':'muted'">{{ i.message }}</div></td></tr></tbody></table></div><el-checkbox v-if="quality.error_rows.length&&mode==='batch'" v-model="exclusionsConfirmed">确认排除以上 {{ quality.error_rows.length }} 条错误记录，保留 {{ quality.valid }} 条有效记录</el-checkbox><div class="two-columns"><div><label>{{ mode==='catalog'?'商品库名称':'任务名称' }}</label><el-input v-model="name" placeholder="例如：九月手机采购商品核对"/></div><div v-if="mode==='batch'"><label>供应商名称</label><el-input v-model="supplier" placeholder="填写供应商来源"/></div></div><div v-if="mode==='batch'" class="two-columns"><div><label>匹配到标准库版本</label><el-select v-model="catalog" class="full" placeholder="先由管理员发布一个标准库版本"><el-option v-for="v in catalogs" :value="v.id" :label="v.label"/></el-select></div><div><label>匹配方案</label><el-select v-model="policy" class="full"><el-option v-for="p in policies" :value="p.id" :label="p.name"/></el-select></div></div><p class="muted"><ShieldCheck :size="13"/> 确认后生成不可变输入版本。再次修正将创建新版本。</p><div class="wizard-footer"><el-button @click="step=1" :disabled="!!savedInput"><ArrowLeft :size="14"/>返回修改</el-button><el-button type="primary" :disabled="!!invalid" :loading="busy" @click="submit">{{ mode==='catalog'?'保存待发布版本':`确认 ${quality.valid} 条并开始匹配` }}</el-button></div></div>
</div></template>
