<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post,put,hasRole,date} from './api'
const accounts=ref<any[]>([]),integrations=ref<any[]>([]),deliveries=ref<any[]>([]),cursor=ref<string|null>(null),credential=ref(''),secret=ref(''),accountOpen=ref(false),integrationOpen=ref(false),attempts=ref<any>(null)
const accountForm=ref({name:'',scopes:['releases:read','deliveries:read','receipts:write'],expires_in_days:30}),integrationForm=ref({name:'',account_id:'',url:'',active:false})
const status:Record<string,string>={QUEUED:'等待通知',SENDING:'正在通知',RETRY:'等待重试',RECEIVED:'通知已接收，等待业务回执',APPLIED:'业务处理成功',PARTIAL:'部分记录失败',REJECTED:'接收方拒绝',MANUAL:'需要人工处理',CANCELLED:'已取消旧通知'}
async function act(fn:()=>Promise<any>){try{await fn()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
async function load(append=false){const d=await api('/deliveries'+(append&&cursor.value?'?cursor='+cursor.value:''));deliveries.value=append?[...deliveries.value,...d.items]:d.items;cursor.value=d.next_cursor;if(hasRole('integration_manager','admin')){const [a,i]=await Promise.all([api('/service-accounts'),api('/integrations')]);accounts.value=a.items;integrations.value=i.items}}
async function createAccount(){await act(async()=>{const a=await post('/service-accounts',accountForm.value);credential.value=a.credential;accountOpen.value=false;await load()})}
async function createIntegration(){await act(async()=>{const i=await post('/integrations',integrationForm.value);secret.value=i.signing_secret;integrationOpen.value=false;await load()})}
async function replay(d:any){await act(async()=>{const {value}=await ElMessageBox.prompt('请先与接收方核对已应用记录，再填写重放原因。重放沿用原事件编号。','重放交付',{inputValidator:v=>!!v?.trim()||'请填写原因'});await post('/deliveries/'+d.id+'/replay',{reason:value});await load()})}
onMounted(()=>act(()=>load()))
</script>
<template><div class="enterprise-section"><div class="section-title"><div><h2>系统交付与业务回执</h2><p class="muted">文件就绪后通知接收方。HTTP 成功仅表示收到通知，实际应用结果以认证回执为准。</p></div><el-button @click="act(()=>load())">刷新交付</el-button></div>
<el-alert v-if="credential||secret" title="凭据仅在本次显示，请交给受控接收端配置并妥善保存。" type="info" :closable="false"/><div v-if="credential||secret" class="panel enterprise-card"><label v-if="credential">服务账号凭据<el-input :model-value="credential" readonly type="password" show-password/></label><label v-if="secret">通知签名密钥<el-input :model-value="secret" readonly type="password" show-password/></label><el-button class="mt16" @click="credential='';secret=''">已保存，关闭凭据显示</el-button></div>
<div v-if="hasRole('integration_manager','admin')" class="enterprise-form-grid"><section class="panel enterprise-card"><div class="section-title"><h3>服务账号</h3><el-button v-if="hasRole('integration_manager')" @click="accountOpen=true">创建服务账号</el-button></div><div v-for="a in accounts" class="enterprise-issue"><div><strong>{{ a.name }}</strong><p>{{ a.active?'已启用':'已停用' }} · 到期 {{ date(new Date(a.expires_at*1000).toISOString()) }}</p><small>{{ a.scopes.join(' / ') }}</small></div><div v-if="hasRole('integration_manager')"><el-button size="small" @click="act(async()=>{credential=(await post('/service-accounts/'+a.id+'/rotate')).credential})">轮换凭据</el-button><el-button size="small" @click="act(async()=>{await put('/service-accounts/'+a.id,{active:!a.active});await load()})">{{ a.active?'停用':'启用' }}</el-button></div></div><el-empty v-if="!accounts.length" description="尚未创建集成专用账号" :image-size="50"/></section><section class="panel enterprise-card"><div class="section-title"><h3>接收系统</h3><el-button v-if="hasRole('integration_manager')" @click="integrationOpen=true">配置接收端</el-button></div><div v-for="i in integrations" class="enterprise-issue"><div><strong>{{ i.name }}</strong><p class="wrap">{{ i.url }}</p><small>{{ i.active?'已启用通知':'通知已停用' }}</small></div><el-button v-if="hasRole('integration_manager')" size="small" @click="act(async()=>{await put('/integrations/'+i.id,{active:!i.active});await load()})">{{ i.active?'停用':'启用' }}</el-button></div><el-empty v-if="!integrations.length" description="尚未配置接收系统" :image-size="50"/></section></div>
<section class="panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>事件 / 发布</th><th>交付状态</th><th>尝试次数</th><th>业务回执</th><th>操作</th></tr></thead><tbody><tr v-for="d in deliveries" :key="d.id"><td>{{ {ARTIFACTS_READY:'发布文件就绪',REVOKED:'发布撤销',INVALIDATED:'发布失效'}[d.kind as 'REVOKED'] }}<small class="cell-sub mono">{{ d.release_id.slice(0,8) }} · {{ d.event_id.slice(0,8) }}</small></td><td>{{ status[d.status] }}<small class="cell-sub">{{ d.last_error }}</small></td><td>{{ d.attempts }}</td><td>{{ d.receipt.message||'尚无回执' }}<small v-for="r in d.receipt.failed_rows||[]" class="cell-sub">{{ r.stable_key }}：{{ r.reason }}</small></td><td><el-button size="small" @click="act(async()=>attempts=await api('/deliveries/'+d.id+'/attempts'))">尝试记录</el-button><el-button v-if="hasRole('integration_manager')&&['MANUAL','RECEIVED','PARTIAL','REJECTED','RETRY'].includes(d.status)" size="small" @click="replay(d)">对账后重放</el-button></td></tr></tbody></table></div><el-empty v-if="!deliveries.length" description="启用接收端并发布文件后，交付记录将在这里显示"/><div class="table-footer"><el-button v-if="cursor" @click="load(true)">更多交付</el-button></div></section>
<el-dialog v-model="accountOpen" title="创建集成专用服务账号" width="550px"><label>名称</label><el-input v-model="accountForm.name"/><label>有效天数</label><el-input-number v-model="accountForm.expires_in_days" :min="1" :max="365"/><label>最小权限</label><el-checkbox-group v-model="accountForm.scopes"><el-checkbox value="releases:read">读取发布</el-checkbox><el-checkbox value="deliveries:read">读取交付</el-checkbox><el-checkbox value="receipts:write">提交回执</el-checkbox></el-checkbox-group><template #footer><el-button type="primary" :disabled="!accountForm.name.trim()||!accountForm.scopes.length" @click="createAccount">创建并显示凭据</el-button></template></el-dialog>
<el-dialog v-model="integrationOpen" title="配置接收系统" width="560px"><label>系统名称</label><el-input v-model="integrationForm.name"/><label>专用服务账号</label><el-select v-model="integrationForm.account_id" class="full"><el-option v-for="a in accounts" :value="a.id" :label="a.name"/></el-select><label>通知地址</label><el-input v-model="integrationForm.url" placeholder="https://接收系统域名/通知路径"/><p class="muted">域名须由部署管理员加入出站白名单。接收方需要验证时间戳签名、按事件幂等处理并提交回执。</p><el-checkbox v-model="integrationForm.active">启用交付通知</el-checkbox><template #footer><el-button type="primary" :disabled="!integrationForm.name.trim()||!integrationForm.account_id||!integrationForm.url" @click="createIntegration">保存并显示签名密钥</el-button></template></el-dialog>
<el-dialog :model-value="!!attempts" @close="attempts=null" title="通知尝试记录" width="600px"><table class="data-table"><thead><tr><th>尝试编号</th><th>HTTP 状态</th><th>错误</th><th>时间</th></tr></thead><tbody><tr v-for="a in attempts?.items"><td>{{ a.number }}</td><td>{{ a.status_code||'—' }}</td><td>{{ a.error||'—' }}</td><td>{{ date(a.created_at) }}</td></tr></tbody></table></el-dialog>
</div></template>
