<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post,put,key,date,hasRole} from './api'
const props=defineProps<{initialBatch?:string}>(),emit=defineEmits(['open'])
const batches=ref<any[]>([]),batch=ref(''),runs=ref<any[]>([]),releases=ref<any[]>([]),current=ref<any>(null),rows=ref<any[]>([]),events=ref<any[]>([]),blockers=ref<any[]>([]),nextBlock=ref<number|null>(null),rowCursor=ref<string|null>(null),busy=ref(false)
const createOpen=ref(false),baseline=ref(''),baseRelease=ref(''),scope=ref(false),scopeReason=ref(''),correctionRuns=ref<string[]>([])
const identityOpen=ref(false),identityKey=ref(''),identityReason=ref(''),identitySource=ref(''),branchOpen=ref(false),branchSource=ref(''),branchOptions=ref<string[]>([]),branchChoice=ref(''),branchReason=ref(''),branchTraces=ref<Record<string,any>>({})
const canDraft=computed(()=>hasRole('operator','publisher')),fullRuns=computed(()=>runs.value.filter(r=>r.status==='SUCCEEDED'&&!r.manifest.correction_scope))
const state:Record<string,string>={DRAFT:'草稿待校验',VALIDATING:'正在校验',READY:'可发布',PUBLISHED:'当前发布',SUPERSEDED:'已被新版替代',REVOKED:'已撤销'}
const resultLabel:Record<string,string>={CONFIRMED:'已匹配',UNMATCHED:'确认无匹配',EXCLUDED:'已排除'}
async function act(fn:()=>Promise<any>){busy.value=true;try{return await fn()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'操作失败')}finally{busy.value=false}}
async function loadBatches(){let cursor:any=null;const all=[];do{const r=await api('/batches?limit=100'+(cursor?'&cursor='+cursor:''));all.push(...r.items);cursor=r.next_cursor}while(cursor);batches.value=all;batch.value=props.initialBatch||all[0]?.id||'';await load()}
async function load(){if(!batch.value)return;const [a,b]=await Promise.all([api('/runs?batch_id='+batch.value+'&limit=100'),api('/releases?batch_id='+batch.value+'&limit=100')]);runs.value=a.items;releases.value=b.items.sort((x:any,y:any)=>y.number-x.number);if(current.value?.batch_id===batch.value)await select(current.value.id);else if(releases.value.length)await select(releases.value[0].id);else current.value=null}
async function select(id:string){current.value=await api('/releases/'+id);const [a,b,c]=await Promise.all([api('/releases/'+id+'/rows'),api('/releases/'+id+'/events'),api('/releases/'+id+'/blockers')]);rows.value=a.items;rowCursor.value=a.next_cursor;events.value=b.items.sort((x:any,y:any)=>y.created_at.localeCompare(x.created_at));blockers.value=c.items;nextBlock.value=c.next_offset}
function openCreate(){baseline.value=fullRuns.value[0]?.id||'';baseRelease.value=releases.value.find(r=>r.status==='PUBLISHED')?.id||'';scope.value=false;scopeReason.value='';correctionRuns.value=[];createOpen.value=true}
async function create(){await act(async()=>{const r=await post('/batches/'+batch.value+'/releases',{baseline_run_id:baseline.value,base_release_id:baseRelease.value||null,correction_run_ids:correctionRuns.value,confirm_scope_change:scope.value,scope_reason:scopeReason.value},key());createOpen.value=false;await post('/releases/'+r.id+'/validate');await load();await select(r.id)})}
async function validate(){await act(async()=>{await post('/releases/'+current.value.id+'/validate');await select(current.value.id)})}
async function publish(){await act(async()=>{await ElMessageBox.confirm(`完整结果 ${current.value.manifest.total} 条，其中有效映射 ${current.value.manifest.mapped} 条。发布后将冻结此版本。`,'发布完整批次',{confirmButtonText:'确认发布',cancelButtonText:'返回核对'});await post('/releases/'+current.value.id+'/publish',{expected_version:current.value.version},key());await load();ElMessage.success('发布已冻结，正在生成全量及增量文件')})}
async function revoke(){await act(async()=>{const {value}=await ElMessageBox.prompt('说明撤销原因，已下载的历史文件仍保留原字节。','撤销发布',{inputValidator:v=>!!v?.trim()||'请填写原因'});await post('/releases/'+current.value.id+'/revoke',{reason:value});await load()})}
async function download(kind:string){await act(async()=>{const blob=await api('/releases/'+current.value.id+'/artifacts/'+kind+'/download');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`批次发布_v${current.value.number}_${kind}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})}
function openIdentity(b:any){identitySource.value=b.root_source_id;identityKey.value='sku:'+b.sku;identityReason.value='';identityOpen.value=true}
async function saveIdentity(){await act(async()=>{await put('/sources/'+identitySource.value+'/identity',{stable_key:identityKey.value,reason:identityReason.value});identityOpen.value=false;await validate()})}
async function openBranch(b:any){branchSource.value=b.root_source_id;branchOptions.value=b.problems.find((p:any)=>p.code==='BRANCH_CONFLICT').choices;branchChoice.value='';branchReason.value='';branchTraces.value={};branchOpen.value=true;await act(async()=>{for(const id of branchOptions.value)branchTraces.value[id]=await api('/sources/'+id+'/trace')})}
async function saveBranch(){await act(async()=>{await put('/releases/'+current.value.id,{...current.value.config,branch_choices:{...current.value.config.branch_choices,[branchSource.value]:{source_id:branchChoice.value,reason:branchReason.value}},expected_version:current.value.version});branchOpen.value=false;await validate()})}
async function moreBlockers(){const r=await api('/releases/'+current.value.id+'/blockers?offset='+nextBlock.value);blockers.value.push(...r.items);nextBlock.value=r.next_offset}
async function moreRows(){const r=await api('/releases/'+current.value.id+'/rows?cursor='+rowCursor.value);rows.value.push(...r.items);rowCursor.value=r.next_cursor}
async function allowScope(){await act(async()=>{const {value}=await ElMessageBox.prompt(`完整来源范围新增 ${current.value.validation.added||0} 条、移除 ${current.value.validation.removed||0} 条，请填写确认依据。`,'确认完整范围变化',{inputValidator:v=>!!v?.trim()||'请填写依据'});await put('/releases/'+current.value.id,{...current.value.config,confirm_scope_change:true,scope_reason:value,expected_version:current.value.version});await validate()})}
let timer:ReturnType<typeof setInterval>
onMounted(()=>{void act(loadBatches);timer=setInterval(()=>{if(current.value&&(current.value.status==='VALIDATING'||current.value.artifacts.some((a:any)=>a.status==='QUEUED')))void select(current.value.id).catch(()=>{})},2000)})
onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="enterprise-section"><div class="section-title"><div><h2>完整结果与发布版本</h2><p class="muted">补数只处理变动记录，正式交付覆盖选定完整输入的所有来源。</p></div><el-button v-if="canDraft" type="primary" :disabled="!fullRuns.length" @click="openCreate">新建发布草稿</el-button></div><div class="button-row"><el-select v-model="batch" filterable placeholder="选择供应商批次" class="grow" @change="load"><el-option v-for="b in batches" :key="b.id" :value="b.id" :label="b.name+' · '+b.supplier"/></el-select><el-button @click="act(load)">刷新发布</el-button></div>
<div class="enterprise-columns"><aside class="panel release-list"><button v-for="r in releases" :key="r.id" :class="{chosen:current?.id===r.id}" @click="select(r.id)"><strong>发布 v{{ r.number }}</strong><span>{{ state[r.status] }}</span><small>{{ r.manifest.total??'—' }} 条完整结果 · {{ date(r.created_at) }}</small></button><el-empty v-if="!releases.length" description="完成审核后创建首个发布草稿" :image-size="60"/></aside><section v-if="current" class="panel enterprise-card grow" v-loading="busy"><div class="section-title"><h3>发布 v{{ current.number }} <span class="status-pill">{{ state[current.status] }}</span></h3><div class="button-row"><el-button v-if="canDraft&&['DRAFT','READY'].includes(current.status)" @click="validate">重新校验</el-button><el-button v-if="hasRole('publisher')&&current.status==='READY'" type="primary" @click="publish">发布完整批次</el-button><el-button v-if="hasRole('publisher')&&['PUBLISHED','SUPERSEDED'].includes(current.status)" type="danger" plain @click="revoke">撤销发布</el-button></div></div>
<el-alert v-if="current.invalidated" title="此发布引用的审核决定已发生变化，请通知接收方并重新发布。历史文件内容保持冻结。" type="error" :closable="false"/>
<div class="release-counts"><div><strong>{{ current.manifest.total??'—' }}</strong><span>完整结果条数</span></div><div><strong>{{ current.manifest.mapped??'—' }}</strong><span>有效映射条数</span></div><div><strong>{{ current.validation.blocker_count??'—' }}</strong><span>发布阻断项</span></div><div><strong>{{ current.manifest.delta_count??'—' }}</strong><span>相对基线的变化</span></div></div><p v-if="current.validation.personal_unsubmitted_drafts" class="muted">另有 {{ current.validation.personal_unsubmitted_drafts }} 条个人草稿尚未提交，不参与本次结果解析。</p>
<div v-if="blockers.length"><h3>需要先解决的问题</h3><div v-for="(b,index) in blockers" :key="index" class="enterprise-issue"><div><strong>{{ b.sku||'完整来源范围' }} <small v-if="b.row_no">原始行 {{ b.row_no }}</small></strong><p v-for="p in b.problems">{{ p.message }}</p></div><div class="button-row"><el-button v-if="b.run_id" size="small" @click="emit('open',{id:b.run_id})">前往处理</el-button><el-button v-if="canDraft&&b.problems.some((p:any)=>['AMBIGUOUS_IDENTITY','DUPLICATE_IDENTITY','IDENTITY_REUSE_REVIEW'].includes(p.code))" size="small" @click="openIdentity(b)">确认来源身份</el-button><el-button v-if="canDraft&&b.problems.some((p:any)=>p.code==='BRANCH_CONFLICT')" size="small" @click="openBranch(b)">选择补数分支</el-button><el-button v-if="canDraft&&b.problems.some((p:any)=>p.code==='SCOPE_CONFIRMATION_REQUIRED')" size="small" @click="allowScope">确认范围变化</el-button></div></div><el-button v-if="nextBlock!==null" @click="moreBlockers">更多问题</el-button></div>
<div v-if="current.artifacts.length"><h3>正式交付文件</h3><div v-for="a in current.artifacts" :key="a.id" class="enterprise-issue"><div><strong>{{ {full:'完整核对结果',mapped:'仅有效映射',delta:'相对基线的增量变更'}[a.kind as 'full'] }}</strong><p>{{ a.count }} 条 · {{ a.status==='SUCCEEDED'?'文件已就绪':a.status==='FAILED'?'生成失败，可重试':'正在生成' }}</p><small v-if="a.file_hash" class="mono wrap">SHA256 {{ a.file_hash }}</small></div><el-button :disabled="a.status!=='SUCCEEDED'" @click="download(a.kind)">下载 CSV</el-button></div><el-button v-if="hasRole('publisher')&&current.artifacts.some((a:any)=>a.status==='FAILED')" @click="act(async()=>{await post('/releases/'+current.id+'/retry-files');await select(current.id)})">重试文件生成</el-button></div>
<details v-if="rows.length" open><summary>完整结果明细（{{ current.manifest.total }} 条）</summary><div class="table-scroll"><table class="data-table"><thead><tr><th>来源商品</th><th>结果状态</th><th>标准商品</th><th>审核依据</th></tr></thead><tbody><tr v-for="r in rows" :key="r.stable_key"><td>{{ r.source_sku }}<small class="cell-sub">{{ r.source_name }}</small></td><td>{{ resultLabel[r.status] }}<small v-if="r.corrected" class="cell-sub">引用补数后的审核</small></td><td>{{ r.target_sku||'—' }}</td><td>{{ r.decision_reason||'已人工确认' }}<small class="cell-sub mono">{{ r.decision_id?.slice(0,8)||'导入排除记录' }} · {{ date(r.decision_at) }}</small></td></tr></tbody></table></div><el-button v-if="rowCursor" @click="moreRows">更多结果</el-button></details><details class="mt16"><summary>发布事件与快照依据</summary><p class="mono wrap">{{ current.snapshot_hash }}</p><p v-for="e in events">{{ date(e.created_at) }} · {{ e.kind }} · {{ e.actor_id?.slice(0,8)||'后台任务' }}</p></details></section></div>
<el-dialog v-model="createOpen" title="创建完整批次发布" width="640px"><label>完整输入运行</label><el-select v-model="baseline" class="full"><el-option v-for="r in fullRuns" :value="r.id" :label="`输入 v${r.revision_number} · ${r.total+r.excluded} 条 · ${date(r.created_at)}`"/></el-select><label>增量基线（已有发布时请选择当前版本）</label><el-select v-model="baseRelease" clearable class="full"><el-option v-for="r in releases.filter(r=>r.published_at)" :value="r.id" :label="`发布 v${r.number} · ${state[r.status]}`"/></el-select><label>补数运行（同一补数存在多次运行时，明确选择）</label><el-select v-model="correctionRuns" multiple class="full"><el-option v-for="r in runs.filter(r=>r.manifest.correction_scope)" :value="r.id" :label="`补数输入 v${r.revision_number} · ${r.total} 条 · ${date(r.created_at)}`"/></el-select><p class="muted">只有一个运行的补数版本会沿来源关系纳入。多个分支必须逐条确认，未审核补数将阻断发布。</p><el-checkbox v-model="scope">确认相对基线的完整来源范围变化</el-checkbox><el-input v-if="scope" v-model="scopeReason" placeholder="说明新增或删除来源的业务依据"/><template #footer><el-button @click="createOpen=false">取消</el-button><el-button type="primary" :disabled="!baseline||(scope&&!scopeReason.trim())" :loading="busy" @click="create">创建并校验</el-button></template></el-dialog>
<el-dialog v-model="identityOpen" title="确认来源的稳定业务身份" width="520px"><p class="muted">缺号、重号或编号复用需要人工消歧。新完整文件中同一业务商品请沿用相同身份。</p><label>稳定业务身份</label><el-input v-model="identityKey"/><label>确认依据</label><el-input v-model="identityReason" type="textarea"/><template #footer><el-button type="primary" :disabled="!identityKey.trim()||!identityReason.trim()" @click="saveIdentity">保存并重新校验</el-button></template></el-dialog>
<el-dialog v-model="branchOpen" title="选择有效补数分支" width="560px"><p class="muted">明确选定一个末端补数记录。其他分支保留历史，不按修改时间自动覆盖。</p><el-select v-model="branchChoice" class="full"><el-option v-for="id in branchOptions" :value="id" :label="branchTraces[id]?'输入 v'+branchTraces[id].revision_number+' · '+branchTraces[id].source.normalized.name:'补数来源 '+id"/></el-select><div v-if="branchTraces[branchChoice]" class="enterprise-card"><strong>资料来源与提交人</strong><p>{{ branchTraces[branchChoice].correction.evidence }}</p><p>{{ branchTraces[branchChoice].actor_name }} · {{ date(branchTraces[branchChoice].correction.at) }}</p><p v-for="(v,f) in branchTraces[branchChoice].correction.fields">{{ f }}：{{ v }}</p></div><label>分支合并依据</label><el-input v-model="branchReason" type="textarea"/><template #footer><el-button type="primary" :disabled="!branchChoice||!branchReason.trim()" @click="saveBranch">确认分支并重新校验</el-button></template></el-dialog>
</div></template>
