<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import {api,post,put,hasRole,labels,claimTokens,session} from './api'
const emit=defineEmits(['open']),items=ref<any[]>([]),reviewers=ref<any[]>([]),batches=ref<any[]>([]),suppliers=ref<any[]>([]),mine=ref(true),batch=ref(''),supplier=ref(''),suggestion=ref(''),cursor=ref<string|null>(null),checked=ref<string[]>([]),assignee=ref(''),reason=ref(''),settings=ref<any>({}),busy=ref(false)
async function act(fn:()=>Promise<any>){busy.value=true;try{await fn()}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function load(append=false){const q=new URLSearchParams({mine:String(mine.value),...(batch.value?{batch_id:batch.value}:{}),...(supplier.value?{supplier_id:supplier.value}:{}),...(suggestion.value?{suggestion:suggestion.value}:{}),...(append&&cursor.value?{cursor:cursor.value}:{})});const r=await api('/review-queue?'+q);items.value=append?[...items.value,...r.items]:r.items;cursor.value=r.next_cursor;if(!append)checked.value=[]}
async function claim(item:any){await act(async()=>{const own=item.claim?.status==='CLAIMED'&&item.claim?.holder_id===session.user.id;const r=await post('/items/'+item.id+(own?'/claim/resume':'/claim'));claimTokens[item.id]=r.claim_token;emit('open',{id:item.run_id,item_id:item.id})})}
async function assign(){await act(async()=>{await post('/review-assignments',{item_ids:checked.value,assignee_id:assignee.value||null,reason:reason.value});reason.value='';ElMessage.success('分派已记录，原领取令牌已失效');await load()})}
async function save(){await act(async()=>{const {require_claim,claim_seconds,queue_limit,storage_bytes,requests_per_minute}=settings.value;await put('/workflow-settings',{require_claim,claim_seconds,queue_limit,storage_bytes,requests_per_minute});ElMessage.success('协作与组织配额已保存')})}
onMounted(()=>act(async()=>{const [r,b,s,w]=await Promise.all([api('/reviewers'),api('/batches'),api('/suppliers'),api('/workflow-settings')]);reviewers.value=r.items;batches.value=b.items;suppliers.value=s.items;settings.value=w;await load()}))
</script>
<template><div class="enterprise-section" v-loading="busy"><div class="section-title"><div><h2>我的待办与审核分派</h2><p class="muted">分派表示责任归属，领取表示正在处理。领取默认 5 分钟有效，工作台每分钟续期。</p></div><el-button @click="act(()=>load())">刷新待办</el-button></div><div class="button-row queue-filters"><el-switch v-model="mine" active-text="我的及未分派" @change="load()"/><el-select v-model="batch" clearable placeholder="所有批次" @change="load()"><el-option v-for="b in batches" :value="b.id" :label="b.name"/></el-select><el-select v-model="supplier" clearable placeholder="所有供应商" @change="load()"><el-option v-for="s in suppliers" :value="s.id" :label="s.name"/></el-select><el-select v-model="suggestion" clearable placeholder="所有问题类型" @change="load()"><el-option v-for="s in ['RECOMMENDED','REVIEW','CONFLICT','NO_CANDIDATE']" :value="s" :label="labels[s]"/></el-select></div>
<section v-if="hasRole('supervisor')" class="panel enterprise-card"><div class="button-row"><el-select v-model="assignee" clearable placeholder="选择审核员（清空表示退回）"><el-option v-for="r in reviewers" :value="r.id" :label="r.name"/></el-select><el-input v-model="reason" placeholder="分派、转交或退回的原因" class="grow"/><el-button type="primary" :disabled="!checked.length||!reason.trim()" @click="assign">处理选中 {{ checked.length }} 条</el-button></div></section>
<section class="panel"><div class="table-scroll"><table class="data-table"><thead><tr><th v-if="hasRole('supervisor')"><el-checkbox :model-value="items.length>0&&checked.length===items.length" @change="(v:any)=>checked=v?items.slice(0,100).map(i=>i.id):[]"/></th><th>来源商品</th><th>问题类型</th><th>责任人 / 分派人</th><th>当前持有人</th><th>待处理时长</th><th>操作</th></tr></thead><tbody><tr v-for="i in items" :key="i.id"><td v-if="hasRole('supervisor')"><el-checkbox :model-value="checked.includes(i.id)" @change="(v:any)=>checked=v?[...checked,i.id]:checked.filter(x=>x!==i.id)"/></td><td>{{ i.source.sku }}<small class="cell-sub">{{ i.source.normalized.name }}</small></td><td>{{ labels[i.suggestion] }}<small class="cell-sub">{{ labels[i.status] }}</small></td><td>{{ i.assignment?.assignee_name||'未分派' }}<small class="cell-sub">{{ i.assignment?.assigned_by_name||'—' }}</small></td><td>{{ i.claim?.status==='CLAIMED'?i.claim.holder_name:'可领取' }}<small v-if="i.claim?.status==='CLAIMED'" class="cell-sub">{{ i.claim.expired?'已超时，可重新领取':'领取中' }}</small></td><td>{{ Math.floor(i.waiting_seconds/60) }} 分钟</td><td><el-button v-if="hasRole('reviewer')" size="small" @click="claim(i)">{{ i.claim?.status==='CLAIMED'&&i.claim?.holder_id===session.user.id?'恢复我的领取':'领取并审核' }}</el-button><el-button v-else size="small" @click="emit('open',{id:i.run_id,item_id:i.id})">查看记录</el-button></td></tr></tbody></table></div><el-empty v-if="!items.length" description="当前筛选下没有待办"/><div class="table-footer"><span>一次最多分派 100 条，双人复核限制始终生效。</span><el-button v-if="cursor" @click="load(true)">更多待办</el-button></div></section>
<details v-if="hasRole('admin')" class="panel enterprise-card"><summary>协作规则与组织配额</summary><div class="enterprise-form-grid"><label>要求先领取再提交<el-switch v-model="settings.require_claim"/></label><label>领取有效期（秒）<el-input-number v-model="settings.claim_seconds" :min="60" :max="900"/></label><label>后台匹配排队上限<el-input-number v-model="settings.queue_limit" :min="1" :max="100"/></label><label>每成员每分钟请求上限<el-input-number v-model="settings.requests_per_minute" :min="30" :max="60000"/></label><label>组织对象存储配额（字节）<el-input-number v-model="settings.storage_bytes" :min="1048576" :max="107374182400"/></label></div><el-button type="primary" @click="save">保存协作设置</el-button><p class="muted">兼容旧版本组织，强制领取初始关闭；有分派或有效领取的记录始终校验持有人。</p></details></div></template>
