<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { FlaskConical, ShieldCheck } from 'lucide-vue-next'
import { api, date, key, post } from './api'
const emit=defineEmits(['changed']),evaluations=ref<any[]>([]),runs=ref<any[]>([]),runId=ref(''),report=ref<any>(null),usage=ref<any>(null),busy=ref(false)
let disposed=false
onUnmounted(()=>{disposed=true})
onMounted(async()=>{try{const[e,r]=await Promise.all([api('/policy-evaluations'),api('/runs?status=SUCCEEDED')]);evaluations.value=e.items;runs.value=r.items;runId.value=r.items[0]?.id||''}catch(e:any){ElMessage.error(e.message)}})
async function promote(e:any){busy.value=true;try{await post('/policies',{name:e.name+' · 已评测版本',engine:'lightgbm',evaluation_id:e.id,high_threshold:e.config.high_threshold,margin:e.config.margin});ElMessage.success('策略版本已发布，可为新任务选择');emit('changed')}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function shadow(e:any){busy.value=true;try{report.value=await post(`/runs/${runId.value}/shadow`,{evaluation_id:e.id},key());while(!disposed&&!['SUCCEEDED','FAILED'].includes(report.value.status)){await new Promise(r=>setTimeout(r,1000));report.value=await api('/shadow-runs/'+report.value.id)}if(report.value.status==='FAILED')ElMessage.error('影子计算失败：'+report.value.error)}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
async function loadUsage(){try{usage.value=await api('/usage-events?run_id='+runId.value)}catch(e:any){ElMessage.error(e.message)}}
function percent(v:any){return v===null||v===undefined?'不可估计':(v*100).toFixed(2)+'%'}
</script>
<template><section class="panel settings-card strategy-lab"><h3><FlaskConical :size="19"/>策略评测与影子对照</h3><p class="muted">学习策略按完整评测版本发布。影子计算供比较候选，不会形成审核决定。</p><el-empty v-if="!evaluations.length" description="尚未注册策略评测报告"/><article v-for="e in evaluations" class="evaluation-card"><div class="section-title"><h4>{{ e.name }}</h4><span class="status-pill" :class="e.report.admission?.eligible?'SUCCEEDED':'REVIEW'">{{ e.report.admission?.eligible?'可进入人工必审试用':'实验状态' }}</span></div><p class="muted">{{ e.report.scope==='controlled_simulation'?'受控模拟数据':e.report.scope }} · {{ date(e.created_at) }} · {{ e.report.dataset_version }}</p><div class="quality-stats"><div><strong>{{ percent(e.report.metrics.top1_precision) }}</strong><span>推荐精确率</span></div><div><strong>{{ percent(e.report.metrics.coverage) }}</strong><span>推荐覆盖率</span></div><div><strong>{{ e.report.metrics.recommended_entities }}</strong><span>独立推荐实体</span></div></div><p class="muted">95% 区间：{{ e.report.metrics.top1_precision_95_ci?.map(percent).join(' – ')||'不可估计' }}。模拟数据不能用于业务策略准入。</p><div class="button-row"><el-select v-model="runId" placeholder="选择影子对照任务"><el-option v-for="r in runs" :label="r.batch_name+' · '+r.id.slice(0,8)" :value="r.id"/></el-select><el-button :loading="busy" :disabled="!runId" @click="shadow(e)">运行影子对照</el-button><el-button type="primary" :loading="busy" :disabled="!e.report.admission?.eligible" @click="promote(e)">发布此评测策略</el-button></div><details class="raw-details"><summary>查看冻结策略及准入结果</summary><pre>{{ JSON.stringify({bundle:e.config,admission:e.report.admission},null,2) }}</pre></details></article><div v-if="report" class="evaluation-card"><h4>影子对照 · {{ report.status==='SUCCEEDED'?'计算完成':report.status==='FAILED'?'计算失败':'后台计算中' }}</h4><div v-if="report.report.n" class="quality-stats"><div><strong>{{ report.report.n }}</strong><span>相同来源输入</span></div><div><strong>{{ report.report.top1_changed }}</strong><span>首选变化</span></div><div><strong>{{ report.report.learning_conflicts }}</strong><span>学习策略冲突</span></div></div><p v-if="report.report.n" class="muted">规则推荐 {{ report.report.rules_recommended }} 条 · 学习策略推荐 {{ report.report.learning_recommended }} 条 · 已有人审结论 {{ report.report.human_decisions }} 条，其中学习首选不一致 {{ report.report.learning_disagrees_with_human }} 条</p></div><div class="section-title"><h4>审核效率观察</h4><el-button :disabled="!runId" @click="loadUsage">读取所选任务的操作统计</el-button></div><p class="muted">操作统计用于安排试用。人工表格对照时间、误确认和中断原因需在试用中独立核验。</p><div v-if="usage" class="quality-stats"><div><strong>{{ usage.review_median_ms===null?'—':(usage.review_median_ms/1000).toFixed(1)+'s' }}</strong><span>单条审核中位时间</span></div><div><strong>{{ usage.search_count }}</strong><span>搜索次数</span></div><div><strong>{{ usage.correction_count }}</strong><span>补数保存次数</span></div></div></section></template>
