<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import {api,post,hasRole,fields,date} from './api'
const suppliers=ref<any[]>([]),batches=ref<any[]>([]),templates=ref<any[]>([]),selected=ref(''),report=ref<any>(null),detail=ref<any>(null),name=ref(''),aliases=ref(''),batchIds=ref<string[]>([]),templateIds=ref<string[]>([]),reason=ref(''),since=ref(''),until=ref('')
async function act(fn:()=>Promise<any>){try{await fn()}catch(e:any){ElMessage.error(e.message)}}
async function load(){const [s,b,t]=await Promise.all([api('/suppliers'),api('/batches'),hasRole('admin')?api('/mapping-templates'):Promise.resolve({items:[]})]);suppliers.value=s.items;batches.value=b.items;templates.value=t.items;if(!selected.value)selected.value=s.items[0]?.id||'';if(selected.value)await quality()}
async function more(){const r=await api('/suppliers/'+selected.value+'/quality?'+new URLSearchParams({cursor:report.value.next_cursor,...since.value?{since:new Date(since.value).toISOString()}:{},...until.value?{until:new Date(until.value+'T23:59:59').toISOString()}:{}}));report.value={...r,items:[...report.value.items,...r.items]}}
async function quality(){report.value=await api('/suppliers/'+selected.value+'/quality?'+new URLSearchParams({...(since.value?{since:new Date(since.value).toISOString()}:{}),...(until.value?{until:new Date(until.value+'T23:59:59').toISOString()}: {})}));detail.value=null}
async function create(){await act(async()=>{const s=await post('/suppliers',{name:name.value,aliases:aliases.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean)});selected.value=s.id;name.value='';aliases.value='';await load()})}
async function bind(){await act(async()=>{await post('/supplier-bindings',{supplier_id:selected.value,batch_ids:batchIds.value,template_ids:templateIds.value,reason:reason.value});ElMessage.success('已按人工确认绑定供应商身份');await quality()})}
const rate=(m:any)=>!m?'等待统计':`${m.numerator}/${m.denominator}（${m.rate===null?'无样本':(m.rate*100).toFixed(1)+'%'}）`
onMounted(()=>act(load))
</script>
<template><div class="enterprise-section"><div><h2>供应商数据质量</h2><p class="muted">按稳定供应商身份统计，展示分子、分母、时间和输入版本。无匹配不直接记为供应商错误。</p></div><div class="button-row"><el-select v-model="selected" filterable placeholder="选择供应商" @change="act(quality)"><el-option v-for="s in suppliers" :value="s.id" :label="s.name"/></el-select><el-input v-model="since" type="date" aria-label="统计开始日期"/><el-input v-model="until" type="date" aria-label="统计结束日期"/><el-button :disabled="!selected" @click="act(quality)">查看质量</el-button></div>
<details v-if="hasRole('admin')" class="panel enterprise-card"><summary>创建供应商及确认历史名称</summary><div class="button-row mt16"><el-input v-model="name" placeholder="供应商正式名称"/><el-input v-model="aliases" placeholder="已确认的历史别名，用逗号分隔"/><el-button :disabled="!name.trim()" @click="create">创建供应商</el-button></div><p class="muted">同名不会自动合并。请确认下列历史批次及模板属于当前选中的供应商。</p><div class="enterprise-form-grid"><el-select v-model="batchIds" multiple filterable placeholder="选择需要绑定的历史批次"><el-option v-for="b in batches" :value="b.id" :label="b.name+' · '+b.supplier"/></el-select><el-select v-model="templateIds" multiple filterable placeholder="选择需要绑定的映射模板"><el-option v-for="t in templates" :value="t.id" :label="t.supplier+' · '+t.name+' v'+t.number"/></el-select><el-input v-model="reason" placeholder="供应商身份确认依据"/><el-button :disabled="!selected||(!batchIds.length&&!templateIds.length)||!reason.trim()" @click="bind">确认绑定</el-button></div></details>
<section v-if="report" class="panel"><p class="muted">周期内共 {{ report.total_versions }} 个输入版本，已生成 {{ report.summary.snapshot_versions }} 份快照；当前加载 {{ report.items.length }} 版。完整输入累计 {{ report.summary.complete_input_rows }} 行，补数子集累计 {{ report.summary.correction_subset_rows }} 行。</p><div class="table-scroll"><table class="data-table"><thead><tr><th>输入版本与范围</th><th>来源条数</th><th>编号重复</th><th>内部规格冲突</th><th>首次审核完成</th><th>补数往返</th><th>处理历时（含等待）</th><th>操作</th></tr></thead><tbody><tr v-for="r in report.items" :key="r.revision_id"><td>输入 v{{ r.number }}<small class="cell-sub">{{ r.scope==='complete_input'?'完整输入':'补数子集' }} · {{ date(r.created_at) }}</small></td><td>{{ r.source_count }}</td><td>{{ rate(r.duplicate_source_ids) }}</td><td>{{ rate(r.internal_conflicts) }}</td><td>{{ rate(r.first_review_completion) }}</td><td>直接 {{ r.corrections?.direct_children??0 }} / 最长链 {{ r.corrections?.longest_chain??0 }} / 累计 {{ r.corrections?.total_descendants??0 }}</td><td>{{ !r.completed_processing_seconds||r.completed_processing_seconds.mean===null?'—':Math.round(r.completed_processing_seconds.mean)+'秒/条' }}<small class="cell-sub">{{ r.completed_processing_seconds?.sample_count??0 }} 条已完成样本</small></td><td><small v-if="r.stale" class="cell-sub">{{ r.status==='PENDING'?'等待生成快照':'审核变化，等待刷新' }}</small><el-button v-if="r.stale&&hasRole('operator','admin','reviewer')" size="small" @click="act(async()=>{await post('/revisions/'+r.revision_id+'/quality/refresh');ElMessage.success('已请求后台刷新，稍后查看质量')})">更新统计</el-button><el-button size="small" @click="act(async()=>detail=await api('/revisions/'+r.revision_id+'/quality'))">下钻明细</el-button></td></tr></tbody></table></div><el-button v-if="report.next_cursor" @click="act(more)">加载更多输入版本</el-button><el-empty v-if="!report.items.length" description="此供应商尚未绑定批次，或所选周期内没有输入"/></section>
<section v-if="detail" class="panel enterprise-card"><h3>输入 v{{ detail.number }} 的字段与问题明细</h3><p class="muted">统计截至 {{ date(detail.observed_at) }} · 输入哈希 {{ detail.input_hash.slice(0,12) }}</p><div class="quality-fields"><div v-for="(m,f) in detail.missing_fields"><strong>{{ fields[f] }}</strong><span>缺失 {{ rate(m) }}</span></div></div><p class="muted">{{ detail.note }}</p><table class="data-table"><thead><tr><th>原始行</th><th>来源编号</th><th>缺失字段</th><th>其他问题</th></tr></thead><tbody><tr v-for="i in detail.issues"><td>{{ i.row_no }}</td><td>{{ i.sku }}</td><td>{{ i.missing.map((f:string)=>fields[f]).join('、')||'—' }}</td><td>{{ i.duplicate?'来源编号重复 ':'' }}{{ i.internal_conflict?'规格内部冲突':'' }}</td></tr></tbody></table><el-button v-if="detail.next_offset!==null" @click="act(async()=>{const r=await api('/revisions/'+detail.revision_id+'/quality?offset='+detail.next_offset);detail={...r,issues:[...detail.issues,...r.issues]}})">更多问题行</el-button></section>
</div></template>
