<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, ArrowRight, Check, CheckCheck, ChevronDown, ChevronRight, CircleAlert, Clock3, Download, FileSearch, FileSpreadsheet, GitCompare, History, Info, RefreshCw, Search, ShieldCheck, Sparkles, Undo2, X } from 'lucide-vue-next'
import CorrectionDesk from './CorrectionDesk.vue'
import { api, date, fields, hasRole, key, labels, post, session, claimTokens } from './api'
const props=defineProps<{runId:string,initialItem?:string}>(),emit=defineEmits(['back','export','revise','open','release'])
const run=ref<any>(null),items=ref<any[]>([]),selected=ref<any>(null),active=ref(''),query=ref(''),status=ref(''),cursor=ref<string|null>(null),busy=ref(false),selectedProduct=ref(''),reason=ref(''),history=ref<any[]>([]),past=ref<any[]>([]),showHistory=ref(false),manual=ref(false),search=ref(''),found=ref<any[]>([]),foundCursor=ref<string|null>(null),selectedManual=ref<any>(null),checked=ref<string[]>([]),manifestOpen=ref(false),compareOpen=ref(false),compareId=ref(''),otherRuns=ref<any[]>([]),comparison=ref<any>(null)
const correctionOpen=ref(false),correctionInitial=ref<any>(null),historyCursor=ref<number|null>(null)
let selectedAt=performance.now()
const claimInfo=ref<any>(null),learning=ref<any>(null)
async function ensureClaim(id:string){if(!claimTokens[id]){const state=await api(`/items/${id}/coordination`);const own=state.claim?.status==='CLAIMED'&&state.claim?.holder_id===session.user.id;const r=await post(`/items/${id}/claim${own?'/resume':''}`);claimTokens[id]=r.claim_token;claimInfo.value=r}return claimTokens[id]}
async function releaseHeld(id:string){const token=claimTokens[id];if(token){delete claimTokens[id];await post(`/items/${id}/claim/release`,{claim_token:token}).catch(()=>{})}}
function track(event:string,duration?:number){void post('/usage-events',{run_id:props.runId,item_id:selected.value?.id,event,duration_ms:duration===undefined?null:Math.round(duration)}).catch(()=>{})}
function openCorrections(initial:any=null){correctionInitial.value=initial;correctionOpen.value=true}
async function nextPending(){let next=items.value.slice(items.value.findIndex(i=>i.id===selected.value?.id)+1).find(i=>['PENDING','REVOKED'].includes(i.status));if(!next&&cursor.value){const old=items.value.length;await refresh(true);next=items.value.slice(old).find(i=>['PENDING','REVOKED'].includes(i.status))}if(next)select(next);else ElMessage.info('当前筛选下已到末尾')}
function shortcuts(e:KeyboardEvent){if(e.altKey&&e.key.toLowerCase()==='j'){e.preventDefault();void nextPending()}}
const isSelf=computed(()=>run.value?.manifest.dual_review&&[run.value?.created_by,run.value?.manifest.batch_creator,run.value?.manifest.revision_creator].includes(session.user.id))
const canReview=computed(()=>hasRole('reviewer')&&run.value?.status==='SUCCEEDED'&&!isSelf.value)
const selectedCandidate=computed(()=>selected.value?.candidates.find((c:any)=>c.product_id===selectedProduct.value))
const canConfirm=computed(()=>canReview.value&&selectedProduct.value&&(!selectedCandidate.value||(!selectedCandidate.value.conflicts.length&&!selectedCandidate.value.missing.length)))
const target=computed(()=>selectedCandidate.value?.product||selectedManual.value)
const confirmed=computed(()=>run.value?.decisions.CONFIRMED||0)
const reviewable=computed(()=>items.value.filter(i=>i.suggestion==='RECOMMENDED'&&i.status==='PENDING'))
const selections=computed(()=>items.value.filter(i=>checked.value.includes(i.id)))
function error(e:any){ElMessage.error(e.message||'操作失败')}
async function refresh(append=false){try{run.value=await api(`/runs/${props.runId}`);const params=new URLSearchParams({details:'false',...(active.value?{suggestion:active.value}:{}),...(status.value?{status:status.value}:{}),...(query.value?{q:query.value}:{}),...(append&&cursor.value?{cursor:cursor.value}:{})});const r=await api(`/runs/${props.runId}/items?${params}`);items.value=append?[...items.value,...r.items]:r.items;cursor.value=r.next_cursor;const current=items.value.find(i=>i.id===selected.value?.id);if(current)await select(current);else if(props.initialItem&&!selected.value)await select(await api(`/items/${props.initialItem}/candidates`));else if(items.value.length)await select(items.value[0]);else selected.value=null;checked.value=[]}catch(e){error(e)}}
let selectionSerial=0
const detailLoading=ref(false)
async function select(i:any){const serial=++selectionSerial;if(selected.value?.id===i.id&&selected.value.version===i.version){detailLoading.value=false;return;}detailLoading.value=true;try{const full=i.summary_only?await api(`/items/${i.id}/candidates`):i;if(serial!==selectionSerial)return;if(selected.value?.id!==i.id)selectedAt=performance.now();if(selected.value?.id&&selected.value.id!==i.id)await releaseHeld(selected.value.id);selected.value=full;const [coordination,risk]=await Promise.all([api(`/items/${i.id}/coordination`),api(`/items/${i.id}/learning-context`)]);claimInfo.value=coordination.claim;learning.value=risk;selectedProduct.value=full.decision?.product_id||full.candidates[0]?.product_id||'';selectedManual.value=null;reason.value='';history.value=[];past.value=[];showHistory.value=false}catch(e){error(e)}finally{if(serial===selectionSerial)detailLoading.value=false}}
async function filter(s:string){active.value=s;await refresh()}
async function decide(action:string){if(!selected.value)return;busy.value=true;try{await post(`/items/${selected.value.id}/decisions`,{action,product_id:action==='confirm'?selectedProduct.value:null,reason:reason.value,expected_version:selected.value.version,claim_token:await ensureClaim(selected.value.id)});delete claimTokens[selected.value.id];claimInfo.value=null;track('review',performance.now()-selectedAt);ElMessage.success({confirm:'已确认映射',unmatched:'已标记当前未匹配',needs_info:'已退回补充资料',revoke:'已撤销原决定'}[action]);await refresh()}catch(e:any){error(e);if(e.code==='CLAIM_LOST'){delete claimTokens[selected.value.id];claimInfo.value=null}if(e.code==='VERSION_CONFLICT'){await refresh();ElMessage.info('已载入最新审核结果，请重新核对')}}finally{busy.value=false}}
async function bulk(){
 const selectedItems=[...selections.value]
 try{
  await ElMessageBox.confirm(`将确认已明确选中的 ${selectedItems.length} 条推荐匹配。服务端会逐条检查规格、权限和版本。`,'批量人工确认',{confirmButtonText:`确认 ${selectedItems.length} 条`,cancelButtonText:'取消'});busy.value=true
  const entries:any[]=[],failures:string[]=[]
  for(const i of selectedItems){try{const full=i.summary_only?await api(`/items/${i.id}/candidates`):i;if(!full.candidates.length)throw new Error('当前记录没有可确认候选');entries.push({item_id:i.id,expected_version:i.version,action:'confirm',product_id:full.candidates[0].product_id,reason:'已逐条核对批量推荐',claim_token:await ensureClaim(i.id)})}catch(e:any){failures.push(`${i.source.sku}：${e.message}`)}}
  const result=entries.length?await post(`/runs/${props.runId}/bulk-decisions`,{items:entries},key()):{succeeded:0,results:[]}
  failures.push(...result.results.filter((r:any)=>!r.ok).map((r:any)=>r.message))
  if(failures.length)ElMessage.warning(`成功 ${result.succeeded} 条，失败 ${failures.length} 条：${failures.join('；')}`);else ElMessage.success(`已确认 ${result.succeeded} 条`)
  await refresh()
 }catch(e:any){if(e!=='cancel'&&e!=='close')error(e)}finally{for(const i of selectedItems)await releaseHeld(i.id);busy.value=false}
}
async function loadHistory(){showHistory.value=!showHistory.value;if(showHistory.value){try{const r=await api(`/items/${selected.value.id}/history`);history.value=r.items;past.value=r.previous_runs;historyCursor.value=r.next_cursor}catch(e){error(e)}}}
async function searchProducts(append=false){track('search');try{const r=await api(`/catalog-versions/${run.value.catalog_version_id}/products?`+new URLSearchParams({q:search.value,...(append&&foundCursor.value?{cursor:foundCursor.value}:{})}));found.value=append?[...found.value,...r.items]:r.items;foundCursor.value=r.next_cursor}catch(e){error(e)}}
function manualSelect(p:any){selectedManual.value=p;selectedProduct.value=p.id;manual.value=false;ElMessage.info('已选择标准商品，确认时将重新校验关键规格')}
async function openCompare(){try{otherRuns.value=(await api('/runs?batch_id='+run.value.batch_id)).items.filter((r:any)=>r.batch_id===run.value.batch_id&&r.id!==run.value.id);compareId.value=otherRuns.value[0]?.id||'';comparison.value=null;compareOpen.value=true}catch(e){error(e)}}
async function compare(append=false){try{const cursor=append&&(comparison.value.next_cursor||comparison.value.ambiguity_next_cursor);const r=await api(`/runs/${props.runId}/compare/${compareId.value}`+(cursor?'?cursor='+cursor:''));comparison.value=append?{...r,changes:[...comparison.value.changes,...r.changes],ambiguities:[...comparison.value.ambiguities,...r.ambiguities]}:r}catch(e){error(e)}}
async function moreHistory(){const r=await api(`/items/${selected.value.id}/history?cursor=${historyCursor.value}`);history.value.push(...r.items);historyCursor.value=r.next_cursor}
let timer:ReturnType<typeof setInterval>,claimTimer:ReturnType<typeof setInterval>
onMounted(async()=>{window.addEventListener('keydown',shortcuts);await refresh();claimTimer=setInterval(async()=>{if(selected.value&&claimTokens[selected.value.id]){try{claimInfo.value=await post(`/items/${selected.value.id}/claim/renew`,{claim_token:claimTokens[selected.value.id]})}catch{delete claimTokens[selected.value.id];claimInfo.value=null;ElMessage.warning('领取已失效，请重新领取')}}},60000);timer=setInterval(()=>{if(run.value&&['QUEUED','RUNNING','CANCEL_REQUESTED'].includes(run.value.status))refresh()},2500)})
onUnmounted(()=>{clearInterval(timer);clearInterval(claimTimer);if(selected.value)void releaseHeld(selected.value.id);window.removeEventListener('keydown',shortcuts)})
</script>

<template><main class="workbench" v-if="run"><div class="workbench-heading"><div><button class="back-link" @click="emit('back')"><ArrowLeft :size="14"/>返回匹配任务</button><h1>{{ run.batch_name }} <span class="status-pill" :class="run.status">{{ labels[run.status] }}</span></h1><p>{{ run.supplier }} <span>·</span> 输入 v{{ run.revision_number }} <span>·</span> {{ run.total }} 条有效记录 <span>·</span> {{ run.excluded }} 条已排除</p></div><div class="button-row"><el-button @click="emit('release',run.batch_id)">批次完整发布</el-button><el-button v-if="hasRole('operator','admin')&&run.status==='SUCCEEDED'" @click="openCorrections()">待补资料</el-button><button class="icon-button bordered" title="刷新结果" @click="refresh()"><RefreshCw :size="16"/></button><el-button @click="openCompare"><GitCompare :size="15"/>版本比较</el-button><el-button type="primary" :disabled="run.status!=='SUCCEEDED'" @click="emit('export',run)"><Download :size="15"/>导出结果</el-button></div></div>
<el-alert v-if="run.manifest.correction_scope" :title="`补数版本：仅含 ${run.total} 条修正记录。完整交付请前往“批次完整发布”。`" type="info" :closable="false"/><div class="workbench-overview"><div><span class="stat-icon green"><CheckCheck :size="17"/></span><strong>{{ confirmed }}</strong><span>/ {{ run.total }} 条已确认</span></div><div class="review-progress"><i :style="{width:(confirmed/run.total*100)+'%'}"></i></div><button class="text-button muted" @click="manifestOpen=true"><ShieldCheck :size="14"/>查看运行版本</button></div>
<div v-if="run.status!=='SUCCEEDED'" class="panel running-panel"><RefreshCw :size="30" :class="{spinning:['RUNNING','QUEUED'].includes(run.status)}"/><h2>{{ labels[run.status] }}</h2><p>已处理 {{ run.processed }} / {{ run.total }} 条 · 失败 {{ run.failed }} 条</p><el-progress :percentage="Math.round(run.processed/run.total*100)"/><p v-if="run.error" class="conflict-text">错误类型：{{ run.error }}</p><p class="muted">{{ ['FAILED','CANCELLED'].includes(run.status)?'部分结果仅供诊断。返回任务列表可创建重试运行。':'后台完成计算后，此处将自动开放审核。' }}</p></div>
<template v-else><div class="review-notice" v-if="!canReview"><ShieldCheck :size="16"/>{{ isSelf?'双人复核已开启。请由另一位审核员处理本批次。':'当前账号可查看匹配依据。请使用审核员账号确认或撤销映射。' }}</div><div class="workbench-filters"><button v-for="(label,id) in {'':'全部记录',RECOMMENDED:'推荐匹配',REVIEW:'需复核',CONFLICT:'规格冲突',NO_CANDIDATE:'暂无候选'}" :class="{selected:active===id}" @click="filter(id)"><span v-if="id" class="filter-dot" :class="id"></span>{{ label }}<em>{{ id?run.suggestions[id]||0:run.total }}</em></button><el-select v-model="status" placeholder="所有审核状态" clearable @change="refresh()" style="width:150px"><el-option v-for="s in ['PENDING','CONFIRMED','UNMATCHED','NEEDS_INFO','REVOKED']" :label="labels[s]" :value="s"/></el-select></div>
<div class="review-grid"><section class="source-list panel"><div class="source-list-header"><h3>来源记录 <span>{{ items.length }}</span><button class="text-button" title="Alt + J" @click="nextPending">下一条待处理</button></h3><el-input v-model="query" placeholder="搜索名称 / 编号" clearable @keyup.enter="refresh()" @clear="refresh()"><template #prefix><Search :size="14"/></template></el-input></div><div v-if="canReview&&reviewable.length" class="batch-select"><el-checkbox :model-value="checked.length===reviewable.length" @change="(v:any)=>checked=v?reviewable.map(i=>i.id):[]">选择已加载推荐（{{ reviewable.length }}）</el-checkbox><button v-if="checked.length" class="text-button" @click="bulk">确认 {{ checked.length }} 条</button></div><div class="source-list-scroll"><button v-for="i in items" :key="i.id" class="source-row" :class="{selected:selected?.id===i.id}" @click="select(i)"><div class="source-row-top"><span class="mono">{{ i.source.sku }}</span><span :class="['mini-status',i.status==='PENDING'?i.suggestion:i.status]">{{ labels[i.status==='PENDING'?i.suggestion:i.status] }}</span></div><strong>{{ i.source.normalized.name }}</strong><div class="source-row-bottom"><span>原始行 {{ i.source.row_no }}</span><el-checkbox v-if="canReview&&i.suggestion==='RECOMMENDED'&&i.status==='PENDING'" :model-value="checked.includes(i.id)" @click.stop @change="(v:any)=>checked=v?[...checked,i.id]:checked.filter(id=>id!==i.id)" :aria-label="'选择记录 '+i.source.sku"/></div></button><el-empty v-if="!items.length" description="此筛选下没有记录" :image-size="65"/><el-button v-if="cursor" class="load-more" @click="refresh(true)">加载更多记录</el-button></div></section>
<template v-if="selected"><section class="source-detail panel" v-loading="detailLoading"><div class="detail-title"><span class="detail-icon"><FileSpreadsheet :size="17"/></span><h3>供应商商品</h3><span class="muted">来源原文</span></div><div class="source-product"><span class="eyebrow">{{ selected.source.generated_sku?'系统记录号':'来源编号' }} · {{ selected.source.sku }}</span><h2>{{ selected.source.normalized.name }}</h2><span class="source-location">工作表原始行 {{ selected.source.row_no }}</span></div><div class="section-title"><h4>标准化字段</h4><span class="tiny-label">手机 SKU</span></div><dl class="spec-list"><template v-for="f in ['brand','model','ram','storage','color','region','pack_count']"><dt>{{ fields[f] }}</dt><dd :class="{'missing-text':!selected.source.normalized[f]}">{{ selected.source.normalized[f]??'信息缺失' }}<small>{{ selected.source.normalized.provenance[f]==='column'?'原始列':selected.source.normalized.provenance[f]==='name'?'名称提取':'' }}</small></dd></template><dt>供应商报价</dt><dd>{{ selected.source.normalized.price||'—' }} {{ selected.source.normalized.currency||'' }}</dd></dl><div class="issue-box" v-if="selected.source.issues.length"><CircleAlert :size="16"/><div><strong>数据质量提示</strong><p v-for="i in selected.source.issues">{{ i.message }}</p></div></div><div v-if="selected.source.correction" class="issue-box"><ShieldCheck :size="16"/><div><strong>补数依据</strong><p>{{ selected.source.correction.evidence }}</p><small>来源原行 {{ selected.source.correction.parent_row_no }} · {{ date(selected.source.correction.at) }}</small></div></div><details class="raw-details"><summary>查看全部原始列<ChevronDown :size="14"/></summary><dl class="spec-list"><template v-for="(v,k) in selected.source.raw"><dt>{{ k }}</dt><dd>{{ v||'—' }}</dd></template></dl></details><div class="source-actions"><button class="text-button" @click="loadHistory"><History :size="15"/>审核历史</button><button v-if="hasRole('operator','admin')" class="text-button" @click="openCorrections(selected)">补充本条资料<ArrowRight :size="13"/></button></div><div v-if="showHistory" class="history-list"><div v-for="e in history"><strong>{{ e.actor_name.split(' · ')[0] }} · {{ {confirm:'确认映射',unmatched:'当前未匹配',needs_info:'退回补充',revoke:'撤销决定'}[e.action as 'confirm'] }}</strong><p>{{ e.reason||'已核对关键规格' }}</p><small>{{ date(e.created_at) }} · v{{ e.seq }}</small></div><el-button v-if="historyCursor" @click="moreHistory">更早的审核记录</el-button><p v-if="!history.length" class="muted">尚无审核记录</p><div v-for="p in past"><strong>历史运行 {{ p.run_id.slice(0,8) }}</strong><p>{{ labels[p.status] }} · {{ labels[p.suggestion] }}</p></div></div></section>
<section class="candidate-panel panel" v-loading="detailLoading"><div class="detail-title"><span class="detail-icon violet"><Sparkles :size="17"/></span><h3>标准库候选</h3><span class="muted">最多 5 个</span><button class="text-button" @click="manual=true;search='';searchProducts()"><Search :size="14"/>手动查找</button></div><div v-if="learning" class="learning-context" :class="learning.risk_level"><div><strong>{{ {CRITICAL:'最高优先',HIGH:'高优先',NORMAL:'普通优先'}[learning.risk_level as 'HIGH'] }} · 风险 {{ learning.risk_score.toFixed(1) }}</strong><small>首选分 {{ learning.top_score??'—' }} · 候选分差 {{ learning.candidate_margin??'—' }}</small></div><span v-for="f in learning.factors">{{ f.label }}：{{ f.detail }}</span></div><div class="candidate-scroll"><div v-if="!selected.candidates.length" class="no-candidates"><FileSearch :size="36"/><h3>当前未找到候选</h3><p>可搜索标准商品库，或退回补充商品信息。</p><el-button @click="manual=true;searchProducts()">搜索标准库</el-button></div><div v-for="c in selected.candidates" class="candidate-card" :class="{chosen:selectedProduct===c.product_id}" @click="selectedProduct=c.product_id;selectedManual=null"><div class="candidate-heading"><span class="radio-dot" :class="{checked:selectedProduct===c.product_id}"></span><strong>{{ c.product.sku }}</strong><span v-if="c.rank===1&&!c.conflicts.length" class="candidate-rank">首选候选</span><span v-if="c.conflicts.length" class="mini-status CONFLICT">{{ c.conflicts.length }} 项冲突</span></div><h4>{{ c.product.normalized.name }}</h4><div class="evidence-chips"><span v-for="e in c.evidence.filter((e:any)=>['model','ram','storage','color','region','pack_count'].includes(e.field))" :class="e.state"><Check v-if="e.state==='same'" :size="11"/><X v-else-if="e.state==='conflict'" :size="11"/>{{ e.text }}</span></div><div v-if="selectedProduct===c.product_id" class="candidate-comparison"><table><thead><tr><th>核对字段</th><th>供应商商品</th><th>标准商品</th></tr></thead><tbody><tr v-for="e in c.evidence" :class="e.state"><td>{{ e.label }}</td><td>{{ e.source??'缺失' }}</td><td>{{ e.target??'缺失' }}</td></tr><tr><td>报价</td><td>{{ selected.source.normalized.price||'—' }} {{ selected.source.normalized.currency }}</td><td>{{ c.product.normalized.price||'—' }} {{ c.product.normalized.currency }}</td></tr></tbody></table><details class="score-details" @click.stop><summary>技术评分与特征 <ChevronDown :size="12"/></summary><p>评分 {{ c.score.toFixed(4) }} · 排名 {{ c.rank }}。评分仅用于候选排序，不是正确性保证。</p><pre>{{ JSON.stringify(c.features,null,2) }}</pre></details></div></div><div v-if="selectedManual" class="candidate-card chosen"><span class="candidate-rank">人工搜索选择</span><h4>{{ selectedManual.normalized.name }}</h4><p class="mono">{{ selectedManual.sku }}</p><dl class="spec-list"><template v-for="f in ['brand','model','ram','storage','color','region','pack_count']"><dt>{{ fields[f] }}</dt><dd>{{ selectedManual.normalized[f]??'缺失' }}</dd></template></dl></div></div>
<div class="decision-area"><div v-if="canReview" class="claim-bar"><span>{{ claimTokens[selected.id]?'本条已领取，每分钟自动续期':'提交时将校验领取资格' }}</span><el-button size="small" v-if="!claimTokens[selected.id]" @click="ensureClaim(selected.id).catch(error)">领取本条</el-button><el-button size="small" v-else @click="releaseHeld(selected.id)">释放领取</el-button></div><div v-if="selected.status!=='PENDING'" class="current-decision"><CheckCheck :size="16"/>当前结论：{{ labels[selected.status] }}<small>版本 {{ selected.version }}</small></div><div v-if="selectedCandidate?.conflicts.length" class="decision-warning"><CircleAlert :size="15"/>关键规格存在冲突，修正输入或另选商品后再确认。</div><div v-else-if="selectedCandidate?.missing.length" class="decision-warning"><Info :size="15"/>关键字段缺失，请补充资料后重新运行。</div><el-input v-model="reason" type="textarea" :rows="2" :disabled="!canReview" maxlength="2000" placeholder="填写审核说明（退回、未匹配、改选或撤销时必填）"/><div class="decision-buttons"><el-button type="primary" :disabled="!canConfirm||detailLoading" :loading="busy" @click="decide('confirm')"><Check :size="16"/>{{ selected.status==='CONFIRMED'?'更新映射':'确认匹配' }}</el-button><el-button :disabled="!canReview||!reason.trim()" :loading="busy" @click="decide('needs_info')">退回补充</el-button><el-dropdown trigger="click" :disabled="!canReview" @command="decide"><el-button :disabled="!canReview">更多<ChevronDown :size="13"/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="unmatched" :disabled="!reason.trim()">标记当前未匹配（需原因）</el-dropdown-item><el-dropdown-item command="revoke" :disabled="!reason.trim()||['PENDING','REVOKED'].includes(selected.status)">撤销原决定（需原因）</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><div class="decision-foot"><ShieldCheck :size="12"/>决定与操作人将写入审核历史</div></div></section></template></div></template>
<el-dialog v-model="manual" title="搜索当前版本的标准商品库" width="770px"><el-input v-model="search" placeholder="搜索名称、型号或内部编号" clearable @keyup.enter="searchProducts()" @clear="searchProducts()"><template #append><el-button @click="searchProducts()">搜索</el-button></template></el-input><div class="manual-results"><button v-for="p in found" @click="manualSelect(p)"><div><strong>{{ p.normalized.name }}</strong><small>{{ p.sku }} · {{ p.normalized.region }} · {{ p.normalized.pack_count }} 件装</small></div><ArrowRight :size="16"/></button><el-empty v-if="!found.length" description="未找到商品，请调整关键词"/><el-button v-if="foundCursor" @click="searchProducts(true)">加载更多</el-button></div></el-dialog>
<el-dialog v-model="manifestOpen" title="运行版本与计算记录" width="700px"><p class="muted">运行定义已冻结，审核结论独立追加。</p><dl class="spec-list"><dt>运行编号</dt><dd class="mono">{{ run.id }}</dd><dt>输入摘要</dt><dd class="mono wrap">{{ run.manifest.input_hash }}</dd><dt>标准化规则</dt><dd>{{ run.manifest.rule_version }}</dd><dt>匹配方案</dt><dd>{{ run.manifest.policy.engine }} · {{ run.manifest.feature_schema }}</dd><dt>双人复核</dt><dd>{{ run.manifest.dual_review?'开启':'关闭' }}</dd><dt>计算用时</dt><dd>{{ ((run.timings.index_seconds||0)+(run.timings.matching_seconds||0)).toFixed(2) }} 秒</dd></dl><details class="raw-details"><summary>完整运行清单</summary><pre>{{ JSON.stringify(run.manifest,null,2) }}</pre></details></el-dialog>
<el-dialog v-model="compareOpen" title="比较同一批次的运行版本" width="820px"><div class="button-row"><el-select v-model="compareId" placeholder="选择另一个运行" class="grow"><el-option v-for="r in otherRuns" :value="r.id" :label="`${date(r.created_at)} · 输入 v${r.revision_number} · ${r.id.slice(0,8)}`"/></el-select><el-button type="primary" :disabled="!compareId" @click="compare()">比较变化</el-button></div><el-empty v-if="!otherRuns.length" description="此批次只有一个运行，新建运行版本后可比较"/><template v-if="comparison"><p class="muted">{{ comparison.identity }} · 共 {{ comparison.total }} 处变化 · {{ comparison.ambiguity_total }} 处编号歧义</p><div class="preview-table"><table class="data-table"><thead><tr><th>来源记录</th><th>当前运行</th><th>对比运行</th></tr></thead><tbody><tr v-for="c in comparison.changes"><td>{{ c.sku }}<small class="cell-sub">原始行 {{ c.row_no }} · {{ c.types.map((t:string)=>({added:'新增',removed:'移除',fields:'字段修改',identity_fields:'身份变化',candidate:'候选变化',decision:'审核变化'}[t])).join('、') }}</small></td><td>{{ labels[c.before?.suggestion]||'无记录' }} · {{ c.before?.target_sku||'—' }}<small class="cell-sub">{{ labels[c.before?.status] }}</small></td><td>{{ labels[c.after?.suggestion]||'无记录' }} · {{ c.after?.target_sku||'—' }}<small class="cell-sub">{{ labels[c.after?.status] }}</small></td></tr></tbody></table></div><div v-for="a in comparison.ambiguities" class="issue-box"><strong>{{ a.sku }}</strong><span>{{ a.reason }} · 原行 {{ a.before_rows.join('、')||'—' }} → {{ a.after_rows.join('、')||'—' }}</span></div><el-button v-if="comparison.next_cursor||comparison.ambiguity_next_cursor" @click="compare(true)">加载更多差异 / 歧义</el-button><el-empty v-if="!comparison.changes.length&&!comparison.ambiguity_total" description="推荐与审核状态没有变化"/></template></el-dialog>
<el-dialog v-model="correctionOpen" title="待补资料与更正草稿" width="1080px" destroy-on-close><CorrectionDesk v-if="correctionOpen" :run="run" :initial="correctionInitial" @complete="r=>{correctionOpen=false;emit('open',r)}"/></el-dialog></main></template>
