import { createRequire } from 'node:module'
import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
const root=path.resolve(import.meta.dirname,'..')
const require=createRequire(path.join(root,'apps/web/package.json'))
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright')
const output=path.resolve(process.env.BROWSER_OUTPUT||path.join(root,'docs/browser'))
fs.mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true})
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:path.join(output,'video'),size:{width:1440,height:1000}},reducedMotion:'reduce'})
const page=await context.newPage(), errors=[]
page.on('pageerror',e=>errors.push(e.message))
page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`)})
const checks=[]
const shot=async name=>{await page.evaluate(()=>window.scrollTo(0,0));return page.screenshot({path:path.join(output,name+'.png'),fullPage:true,animations:'disabled'})}
async function login(role){await page.getByRole('button',{name:role,exact:true}).click();await page.getByRole('button',{name:'登录工作空间',exact:true}).click();await page.getByRole('heading',{name:'匹配任务',exact:true}).waitFor()}
try{
 await page.goto(process.env.APP_URL||'http://127.0.0.1:18765')
 await page.getByRole('button',{name:'登录工作空间',exact:true}).waitFor();await shot('01-login')
 await login('数据专员');checks.push('operator login');await shot('02-dashboard')
 await page.getByRole('button',{name:'新建匹配任务',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.locator('input[type=file]').setInputFiles(path.join(root,'samples/供应商商品表.csv'))
 await dialog.getByRole('button',{name:'上传并配置字段'}).click()
 await dialog.getByRole('button',{name:'校验数据'}).click()
 await dialog.getByText(/错误行不会参与匹配：共 1 行/).waitFor()
 await shot('03-import-validation')
 await dialog.getByText('确认排除以上 1 条错误记录，保留 29 条有效记录',{exact:true}).click()
 const name='浏览器验收 · 手机供应商匹配 '+Date.now()
 await dialog.getByPlaceholder('例如：九月手机采购商品核对').fill(name)
 await dialog.getByPlaceholder('填写供应商来源').fill('演示供应商（构造数据）')
 await dialog.getByRole('button',{name:'确认 29 条并开始匹配'}).click()
 await page.getByRole('heading',{name:new RegExp(name)}).waitFor()
 await page.locator('.review-grid').waitFor({timeout:45000})
 checks.push('upload + mapping + explicit exclusions + worker completion')
 await page.getByRole('button',{name:'确认匹配',exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'确认匹配',exact:true}).isDisabled(),true)
 checks.push('operator review disabled')
 await page.getByRole('button',{name:'退出并切换账号'}).click();await login('审核员')
 await page.getByRole('button',{name,exact:true}).first().click()
 await page.locator('.review-grid').waitFor()
 await page.locator('.workbench-filters').getByRole('button',{name:/推荐匹配/}).click()
 await page.locator('.source-row').first().click()
 await page.getByRole('button',{name:'确认匹配',exact:true}).click()
 await page.getByText('当前结论：已确认').waitFor();checks.push('reviewer confirmation')
 await shot('04-workbench-confirmed')
 await page.locator('.workbench-filters').getByRole('button',{name:/规格冲突/}).click()
 await page.locator('.source-row').first().click()
 assert.equal(await page.getByRole('button',{name:'确认匹配',exact:true}).isDisabled(),true)
 await shot('05-spec-conflict');checks.push('hard conflicts visible and confirmation disabled')
 await page.getByPlaceholder('填写审核说明（退回、未匹配、改选或撤销时必填）').fill('容量与标准商品不一致，请供应商补充准确配置')
 await page.getByRole('button',{name:'退回补充',exact:true}).click()
 await page.getByText('当前结论：待补充').waitFor();checks.push('return for information')
 await page.getByRole('button',{name:'手动查找',exact:true}).click()
 await page.getByRole('dialog').getByPlaceholder('搜索名称、型号或内部编号').fill('STD-0001')
 await page.getByRole('dialog').getByRole('button',{name:'搜索',exact:true}).click()
 await page.getByRole('dialog').locator('.manual-results>button').first().waitFor()
 await page.getByRole('dialog').getByRole('button',{name:/Close this dialog|关闭此对话框/}).click();checks.push('manual catalog search')
 await page.getByRole('button',{name:'导出结果',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'确认生成 1 条记录',exact:true}).click()
 await page.getByRole('heading',{name:'导出记录',exact:true}).waitFor()
 const downloadButton=page.getByRole('button',{name:'下载文件',exact:true}).first()
 await downloadButton.waitFor({timeout:45000})
 const [download]=await Promise.all([page.waitForEvent('download'),downloadButton.click()])
 await download.saveAs(path.join(output,'browser-export.xlsx'));checks.push('snapshot export + authorized download')
 await shot('06-export')
 await page.getByRole('button',{name:'匹配任务',exact:false}).first().click()
 await page.getByRole('button',{name,exact:true}).first().click()
 await page.locator('.workbench-filters').getByRole('button',{name:/推荐匹配/}).click()
 await page.locator('.source-row').filter({hasText:'已确认'}).first().click()
 await page.getByPlaceholder('填写审核说明（退回、未匹配、改选或撤销时必填）').fill('验收撤销测试，保留原决定历史')
 await page.getByRole('button',{name:'更多',exact:true}).click()
 await page.getByRole('menuitem',{name:'撤销原决定（需原因）'}).click()
 await page.getByText('当前结论：已撤销').waitFor();checks.push('revoke decision')
 await page.getByRole('button',{name:'导出记录',exact:true}).click()
 await page.getByText('历史快照 · 决定已变化').first().waitFor();checks.push('old export stale marker')
 if(process.env.ENTERPRISE_BULK==='true'){
  await page.getByRole('button',{name:'匹配任务',exact:false}).first().click();await page.getByRole('button',{name,exact:true}).click();await page.locator('.workbench-filters').getByRole('button',{name:/推荐匹配/}).click();await page.getByText(/选择已加载推荐/).click();const send=page.waitForResponse(r=>r.url().endsWith('/bulk-decisions')&&r.status()===200);send.catch(()=>{});await page.locator('.source-list').getByRole('button',{name:/^确认 \d+ 条$/}).click();await page.getByRole('button',{name:/^确认 \d+ 条$/}).last().click();const result=await(await send).json();assert(result.succeeded>0&&result.failed===0);checks.push('bulk claims and per-item review outcomes');await shot('09-bulk-review')
 }
 await page.getByRole('button',{name:'退出并切换账号'}).click();await login('管理员')
 await page.getByRole('button',{name:'组织设置',exact:true}).click()
 await page.getByText('组织成员').waitFor();await shot('07-settings');checks.push('admin member management')
 await page.getByRole('button',{name:'匹配任务',exact:false}).first().click()
 await page.setViewportSize({width:390,height:844})
 await page.getByRole('heading',{name:'匹配任务',exact:true}).waitFor();await shot('08-mobile')
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('390px responsive viewport without page overflow')
 assert.deepEqual(errors,[])
 fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed:true,checks,errors,at:new Date().toISOString()},null,2))
 console.log(JSON.stringify({passed:true,checks},null,2))
}catch(e){await shot('failure');fs.writeFileSync(path.join(output,'failure.html'),await page.content());throw e}
finally{await context.close();await browser.close()}
