import {createRequire} from 'node:module'
import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
const root=path.resolve(import.meta.dirname,'..'),require=createRequire(path.join(root,'apps/web/package.json'))
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),base=process.env.APP_URL||'http://127.0.0.1:18766',output=path.join(root,'docs/v13/browser')
fs.mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),checks=[],errors=[]
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(r.status()+' '+r.url())})
const shot=async name=>page.screenshot({path:path.join(output,name+'.png'),fullPage:true,animations:'disabled'})
async function login(role){await page.getByRole('button',{name:role,exact:true}).click();await page.getByRole('button',{name:'登录工作空间',exact:true}).click();await page.getByRole('heading',{name:'匹配任务',exact:true}).waitFor()}
async function tab(name){await page.getByRole('button',{name,exact:true}).click()}
try{
 await page.goto(base);await login('管理员');await tab('发布与协作');await tab('统一待办');await page.getByRole('heading',{name:'统一待办',exact:true}).waitFor();await shot('01-todos');checks.push('unified canonical todo list and action navigation')
 await page.locator('tbody tr').filter({hasText:'发布影响'}).first().getByRole('button',{name:'打开处理'}).click();const impact=page.getByRole('dialog',{name:'处理标准库影响'});await impact.getByText('受影响来源共 2 条',{exact:false}).waitFor();if(await impact.locator('.el-select').count()){await impact.locator('.el-select').click();await page.getByRole('option',{name:'发布 v2 · 已发布',exact:true}).click();await impact.getByRole('textbox',{name:'影响处置理由'}).fill('浏览器隔离验收：全部来源在新库复核后发布');await impact.getByRole('button',{name:'完成前检查'}).click();await impact.getByText('关联、范围、审核及发布依据检查通过，可以保存。',{exact:true}).waitFor();await impact.getByRole('button',{name:'保存影响处置'}).click();}await impact.getByText(/下游待确认/).waitFor();await shot('02-impact-disposition');checks.push('release impact preflight, exact affected scope, replacement and downstream pending state');await impact.getByRole('button',{name:/Close this dialog|关闭此对话框/}).click()
 await tab('系统交付');await page.getByRole('button',{name:'处理对账',exact:true}).first().click();const recon=page.getByRole('dialog',{name:'业务回执对账'});await recon.getByRole('textbox',{name:'对账依据'}).fill('已核对事件与版本，模拟下游暂未回传业务回执');await recon.getByRole('button',{name:'记录已核对'}).click();await page.getByText('已记录对账进展，成功状态仍由接收方回执确认',{exact:true}).waitFor();await shot('03-reconciliation');checks.push('timeout reconciliation records progress without marking applied');await recon.getByRole('button',{name:/Close this dialog|关闭此对话框/}).click()
 await tab('标准库影响');await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'原标准库版本'})}).click();await page.locator('#'+await page.getByRole('combobox',{name:'原标准库版本'}).getAttribute('aria-controls')).getByRole('option').filter({hasText:/ v1$/}).click();await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'新标准库版本'})}).click();await page.locator('#'+await page.getByRole('combobox',{name:'新标准库版本'}).getAttribute('aria-controls')).getByRole('option').filter({hasText:/ v2$/}).click();await page.getByRole('button',{name:'准备待确认对应'}).click();await page.getByText('准备状态：待确认',{exact:false}).waitFor({timeout:30000});await shot('04-paged-catalog');checks.push('catalog identity suggestions generated in background with bounded page')
 await page.getByRole('textbox',{name:'身份对应核对依据'}).fill('浏览器隔离测试：逐组检查身份对应')
 for(const name of ['身份及内容一致','身份字段变化']){await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'确认分组'})}).click();await page.locator('#'+await page.getByRole('combobox',{name:'确认分组'}).getAttribute('aria-controls')).getByRole('option',{name,exact:true}).click();await page.getByRole('button',{name:'按依据确认当前分组'}).click();await page.getByRole('button',{name:'刷新对应'}).click()}
 await page.getByRole('spinbutton',{name:'确认停用数量'}).fill('0');await page.getByRole('button',{name:'提交影响分析',exact:true}).click();await page.getByRole('button',{name:'确认提交',exact:true}).click();await page.getByText('影响分析已提交',{exact:true}).waitFor();checks.push('group confirmation and explicit retirement count submission')
 await tab('供应商质量');await page.getByText(/周期内共/).waitFor();await page.getByRole('button',{name:'下钻明细'}).first().click();await page.getByText(/统计截至/).waitFor();await shot('05-quality-snapshot');checks.push('quality dates, correction depth metrics and complete history coverage')
 await page.getByRole('button',{name:'退出并切换账号'}).click();await login('数据专员');await tab('发布与协作');await tab('统一待办');await page.locator('tbody tr').filter({hasText:'待补资料'}).first().getByRole('button',{name:'打开处理'}).click();await page.getByRole('button',{name:'补充本条资料',exact:true}).click();await page.getByRole('button',{name:'下载问题行模板'}).waitFor();checks.push('todo opens source correction workspace')
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下载问题行模板'}).click();const downloaded=await downloadPromise;const csvPath=path.join(output,'return-template.csv');await downloaded.saveAs(csvPath)
 const returnedPath=path.join(output,'returned.csv');execFileSync(process.env.PYTHON||'python3',['-c',"import csv,sys; rows=list(csv.DictReader(open(sys.argv[1],encoding='utf-8-sig'))); [r.update(price='7777',资料来源='隔离浏览器回填验证') for r in rows]; f=open(sys.argv[2],'w',encoding='utf-8-sig',newline=''); w=csv.DictWriter(f,fieldnames=list(rows[0])); w.writeheader(); w.writerows(reversed(rows)); f.close()",csvPath,returnedPath]);const uploaded=page.waitForResponse(r=>r.url().endsWith('/corrections/return')&&r.request().method()==='POST');await page.getByLabel('上传回填模板',{exact:true}).setInputFiles(returnedPath);const result=await(await uploaded).json();assert(result.count>0&&result.requires_manual_submit);await page.getByText(`已回收 ${result.count} 条，待人工确认提交`,{exact:true}).waitFor();await shot('06-return-template');checks.push('signed template download and unordered return upload create drafts only');assert(fs.readFileSync(csvPath,'utf8').includes('verification'))
 await page.setViewportSize({width:390,height:844});await shot('07-mobile');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2));checks.push('mobile viewport has no page overflow')
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed:true,checks},null,2));console.log(JSON.stringify({passed:true,checks},null,2))
}catch(e){await shot('failure');fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed:false,checks,error:String(e),errors},null,2));throw e}
finally{await context.close();await browser.close()}
